<?php
    $list_headers = $block->getData('listheaders');
    $list_values = $block->getData('listvalues');
    $list_headers = explode("||", $list_headers);
    $list_values = explode("||", $list_values);
    $headlineCustomCssStyle = '';
    $selectedHeaderTextColor = '';
    $selectedDetailTextColor = '';
    $html = '';
    $selectedListValueTextSize = '';
    $selectedHeaderValueTextSize = '';
    $selectedListValueTextStyle = '';
    $selectedHeaderTextStyle = '';

    $selectedHeaderValueTextSize = $block->getData('headertextsize');

    $selectedListValueTextSize = $block->getData('listvaluetextsize');

    $selectedHeaderTextColor = $block->getData('headerstextcolor');

    $selectedDetailTextColor = $block->getData('listvaluetextcolor');

    //If value exists for listvaluetextstyle pull in the value and replace the comma for a space
    if($block->getData('listvaluetextstyle') != ''):
        $selectedListValueTextStyle = str_replace(',' , '', $block->getData('listvaluetextstyle'));
    endif;

    //If value exists for listvaluetextstyle pull in the value and replace the comma for a space
    if($block->getData('headerTextStyle') != ''):
        $selectedHeaderTextStyle = str_replace(',' , '', $block->getData('headerTextStyle'));
    endif;




    $i = 0;

    foreach($list_headers as $header):
        $html .= '<li><span class="specListHeaderContainer" style="color:' . trim($selectedHeaderTextColor) . ';' . trim($selectedHeaderValueTextSize) . trim($selectedHeaderTextStyle) . '">' . trim($header) . '</span> '
          . '<span class="specListValueContainer" style="color:' . trim($selectedDetailTextColor) . ';' . trim($selectedListValueTextSize) . trim($selectedListValueTextStyle) . '">' . trim($list_values[$i]) . '</span>' .
          '</li>';
        $i++;
    endforeach;


    //If headlinetextstyle exists then set to customCssStyles
    if($block->getData('headlinetextstyle') != ''):
      $headlineCustomCssStyle = $block->getData('headlinetextstyle');
    endif;
?>

<section class="product-info-container align-top">
    <div class="product-info grid col-2">
        <h2 style="
            <?php
              $headlinestylevalues = explode(',', $headlineCustomCssStyle);
              foreach($headlinestylevalues as $headlinevalue) {
                echo $headlinevalue;
              }
            ?>
          color:<?php echo $block->getData('bannerheadlinecolor'); ?>;"
        >
          <?php echo $block->getData('headline'); ?>
        </h2>
        <ul class="list-info">
            <?php echo $html; ?>
        </ul>
    </div>
</section>