# Maybe this should be a NodePort
apiVersion: v1
kind: Service
metadata:
  name: local-mysql-service
  labels:
    app: local-magento
spec:
  ports:
    - port: 3306
  selector:
    app: local-magento
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: magento-local-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-magento-mysql
  labels:
    app: local-magento
spec:
  selector:
    matchLabels:
      app: local-magento
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: local-magento
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.25
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
