<div class="sp-home-page">
	<div class="sp-home__how-it-works sp-container sp-my-20">
		<h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
			A Subscription Lawn Care Plan Made Just for Your Yard
		</h2>

		<div class="md:sp-flex md:sp--mx-4">
			<div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-4 md:sp-px-4 sp-text-center">
				<img src="https://test_magento_image_repo.storage.googleapis.com/size.png" alt="Tell us about your lawn">
				<h3 class="sp-h3">Tell us about your lawn.</h3>
				<p class="sp-text-sm">We'll ask you some easy questions about your location, grass type, and lawn condition. Don't worry if you're not sure—we've got tools to help you figure it out.</p>
			</div>
			<div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-4 md:sp-px-4 sp-text-center">
				<picture>
					<source srcset="https://test_magento_image_repo.storage.googleapis.com/color.png"
							media="(min-width: 768px)">
					<img src="https://test_magento_image_repo.storage.googleapis.com/mobile.png" alt="Personalized plan" />
				</picture>
				<h3 class="sp-h3">See your personalized plan.</h3>
				<p class="sp-text-sm">We'll give you an easy-to-follow plan—created specifically for your yard—that can help you grow the kind of lawn your neighbors will envy.</p>
			</div>
			<div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-4 md:sp-px-4 sp-text-center">
				<img src="https://test_magento_image_repo.storage.googleapis.com/calendar.png" alt="Products arrive">
				<h3 class="sp-h3">Get what you need when you need it.</h3>
				<p class="sp-text-sm">Each product in your lawn care plan will arrive right when it should be applied. Just open the package, apply to your lawn, and voila! You're done.</p>
			</div>
		</div>

		<div class="sp-text-center sp-mt-8 md:sp-mt-0">
			<a href="<?php echo $block->escapeUrl($block->getUrl('how-it-works')) ?>" class="sp-button sp-button--primary">TELL ME MORE</a>
		</div>
	</div>

	<div class="sp-home__what-to-expect sp-my-20 sp-pb-12 md:sp-mx-4 lg:sp-pb-8">
		<div class="sp-bg-green-4">
			<div class="sp-container sp-py-8">
				<h2 class="sp-h2 sp-max-w-md sp-mx-auto sp-text-center sp-text-green-1 sp-home__what-to-expect-heading">Lawn Care Made Beautifully Simple</h2>

				<div class="md:sp-flex sp-items-center md:sp--mx-4 sp-mb-16">
					<div class="md:sp-px-4 md:sp-w-1/2 sp-text-center">
						<img
							alt="Season Animation"
							class="sp-block sp-mx-auto"
							src="https://test_magento_image_repo.storage.googleapis.com/Animation.png"
						/>
					</div>
					<div class="md:sp-px-4 md:sp-w-1/2">
						<p class="sp-h3">The Scotts Lawn Care Program is the easiest way to grow a thicker, greener lawn with deeper roots and fewer weeds. What you put in: 10 to 15 minutes of care a few times a year. What you get out: The kind of gorgeous lawn you'd get if you hired a professional.</p>
					</div>
				</div>
			</div>
			<div class="sp-max-w-lg sp-mx-auto sp-px-4 md:sp-px-0">
				<div class="sp-relative sp-home__what-to-expect-img">
					<img
						alt="What To Expect"
						class="sp-block sp-mx-auto"
						src="https://test_magento_image_repo.storage.googleapis.com/WhatToExpect-Img.png"
					/>
				</div>
			</div>
		</div>
		<div class="sp-container sp-py-8 sp-text-center">
			<h3 class="sp-h3">What to Expect</h3>
			<p class="sp-p1 sp-max-w-md sp-mx-auto">Sign up for Scotts Program and you'll receive exactly what your lawn needs at just the right time to apply it. Kiss confusion goodbye—we do all the thinking and planning for you.</p>
			<a href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>" class="sp-button sp-button--primary sp-button--get-started sp-relative sp-text-center sp-mt-4">GET YOUR PLAN</a>
		</div>
	</div>

	<div class="sp-home__history sp-bg-green-4 sp-mb-24 sp-mt-24 lg:sp-mt-0">
		<div class="sp-container sp-py-16">
			<div class="sp-home__history-container sp-flex sp-items-center sp-mx-auto">
				<div class="sp-home__history-description lg:sp-w-1/2 sp-px-4 sp-text-center lg:sp-text-left">
					<h3 class="sp-h3 sp-max-w-xs sp-mx-auto sp-text-center">Over 150 Years of Lawn Care Innovation</h3>
					<p class="sp-text-center">Scotts has been your trusted lawn care partner for more than 150 years—and we put that expertise and innovative spirit to work for you with a personalized Lawn Care Program. Additionally, we offer our exclusive No Quibble Guarantee on every product we sell.</p>
					<div class="sp-mt-8 sp-text-center">
						<a href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>" class="sp-button sp-button--primary sp-button--get-started sp-mb-12 sp-relative">CUSTOMIZE YOUR PLAN</a>
					</div>
				</div>
				<div class="sp-home__history-date sp-mb-8 lg:sp-mb-0">
					<div class="sp-text-center">
						<svg class="line-1" id="line-1-id" width="4px" viewBox="0 0 2 174" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" fill="none" fill-rule="evenodd">
								<g id="D-HomePage-" transform="translate(-639.000000, -3435.000000)" stroke="#1d5632" stroke-width="2">
									<g id="Expertise" transform="translate(0.000000, 3056.000000)">
										<g id="Line-Animation" transform="translate(566.000000, 128.000000)">
											<line x1="74" y1="252" x2="74" y2="424" id="Line-2"></line>
										</g>
									</g>
								</g>
							</g>
						</svg>
					</div>

					<p id="countdown" class="sp-home__countdown">1868</p>

					<div class="sp-hide lg:sp-block sp-text-center">
						<svg class="line-2" id="line-2-id" width="4px" viewBox="0 0 2 174" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
							<g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" stroke-linecap="square">
								<g id="D-HomePage-" transform="translate(-639.000000, -3435.000000)" stroke="#1d5632" stroke-width="2">
									<g id="Expertise" transform="translate(0.000000, 3056.000000)">
										<g id="Line-Animation" transform="translate(566.000000, 128.000000)">
											<line x1="74" y1="252" x2="74" y2="424" id="Line-3"></line>
										</g>
									</g>
								</g>
							</g>
						</svg>
					</div>
				</div>
				<div class="sp-home__history-image sp-w-full lg:sp-w-1/2 sp-px-4">
                    <div
                        class="sp-aspect-ratio sp-aspect-ratio--1x1"
                        id="trigger-anim"
                    >
                        <img
                            alt="History"
                            class="season-img sp-aspect-ratio--object"
                            src="https://test_magento_image_repo.storage.googleapis.com/history_img3.jpg"
                        />
                        <img
                            alt="History"
                            class="season-img sp-aspect-ratio--object"
                            src="https://test_magento_image_repo.storage.googleapis.com/history_img2.jpg"
                        />
                        <img
                            alt="History"
                            class="season-img sp-aspect-ratio--object"
                            src="https://test_magento_image_repo.storage.googleapis.com/history_img1.jpg"
                        />
                        <img
                            alt="History"
                            class="season-img sp-aspect-ratio--object"
                            src="https://test_magento_image_repo.storage.googleapis.com/history_img4.jpg"
                        />
                        <img
                            alt="History"
                            class="season-img sp-aspect-ratio--object"
                            src="https://test_magento_image_repo.storage.googleapis.com/history_img5.jpg"
                        />
                    </div>
				</div>
			</div>
		</div>
	</div>

	<div class="sp-home__apps sp-overflow-hidden sp-mt-12">
		<div class="sp-container">
			<div class="sp-flex sp-flex-column md:sp-flex-row sp-items-center md:sp--mx-8">
				<div class="sp-order-1 md:sp-order-0 md:sp-w-1/2 sp-px-8">
					<div>
						<img
							alt="Mobile Apps"
							class="sp-block sp-max-w-xs sp-mx-auto"
							src="https://test_magento_image_repo.storage.googleapis.com/Apps-img.jpg"
						/>
					</div>
				</div>
				<div class="sp-order-0 md:sp-order-1 md:sp-w-1/2 sp-pb-8 md:sp-pb-0 sp-px-8">
					<div class="sp-inline-block sp-mx-auto sp-text-center md:sp-text-left">
						<h3 class="sp-h3">Lawn Care at Your Fingertips</h3>
						<p>The perfect companion to track your lawn care plan. Download the My Lawn app to get application reminders, expert lawn care tips, and more.</p>
						<div class="sp-flex sp-justify-center md:sp-justify-start">
							<a href="https://apps.apple.com/us/app/my-lawn-a-guide-to-lawn-care/id372269879?mt=8" target="_blank">
								<img
									alt="App Store"
									class="sp-app-image sp-mr-4"
									src="https://test_magento_image_repo.storage.googleapis.com/badge--appstore.png"
								/>
							</a>
							<a href="https://play.google.com/store/apps/details?id=com.scotts.lawnapp" target="_blank">
								<img
									alt="Google Play"
									class="sp-app-image"
									src="https://test_magento_image_repo.storage.googleapis.com/badge--googleplay.png"
								/>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>
<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "homepage": {
                        "component": "SMG_SPV2HomePageWidget/js/homepage"
                    }
                }
            }
        }
	}
</script>
