<?php
$orderId = $this->getRequest()->getParam('order_id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->load($orderId);
?>
<section class="admin__page-section order-view-subscription-information">
    <div class="admin__page-section-title">
        <span class="title">Subscription Details</span>
    </div>
    <div class="admin__page-section-content">
    	<table class="admin__table-secondary order-information-table">
    		<tbody>
    			<tr>
    				<th>Gigya ID</th>
    				<td><?= $order->getGigyaId() ?></td>
    			</tr>
    			<tr>
    				<th>Master Subscription ID</th>
    				<td><?= $order->getMasterSubscriptionId() ?></td>
    			</tr>
    			<tr>
    				<th>Subscription ID</th>
    				<td><?= $order->getSubscriptionId() ?></td>
    			</tr>
    			<tr>
    				<th>Is Addon Subscription?</th>
    				<td><?= $order->getSubscriptionAddon() ?></td>
    			</tr>
    			<tr>
    				<th>Ship Date</th>
    				<td><?= $order->getShipDate() ?></td>
    			</tr>
    		</tbody>
    	</table>
    </div>
</section>