<?php
/*
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store     = $storeManager->getStore()->getCode();
$helper = $block->getHelper();
if (!$helper->isPlegoEnabled($store)) {
	return;
}
?>
<div data-role="plego-launch-fpc" style="display:none;">

</div>
<script type="text/x-magento-init">
    {"[data-role='plego-launch-fpc']": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}}
</script>
<?php */ ?>