<div class="sp-quiz sp-bg-green-1 sp-flex sp-text-white">
    <div class="sp-quiz__wrapper sp-flex sp-flex-column sp-h-full sp-w-full" data-bind="scope: 'quiz'">
        <div
            class="sp-quiz__content sp-flex-auto sp-py-12"
            data-bind="if: !quiz.complete()"
        >
            <!-- ko template: "SMG_Recommendations/questiontypes/1-single-select" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/2-multi-select" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/3-slider" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/4-entry" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/5-zone" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/5-b-zone" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/6-area" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/7-single-select-with-images" --><!-- /ko -->
            <!-- ko template: "SMG_Recommendations/questiontypes/8-multi-select-with-images" --><!-- /ko -->
        </div>

        <!--Final Screen-->
        <div
            class="sp-quiz__content sp-flex-auto sp-py-12"
            data-bind="if: quiz.complete()"
        >
            <!-- ko template: "SMG_Recommendations/final" --><!-- /ko -->
        </div>
        <!-- ko template: "SMG_Recommendations/footer" --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "quiz": {
                        "component": "SMG_Recommendations/js/quiz"
                    }
                }
            }
        }
    }
</script>
