<?php
    $cols = 1;
    if($block->getData('prodnametwo') != '' && $block->getData('prodnamethree') != ''):
        $cols = 3;
    elseif($block->getData('prodnametwo') != '' || $block->getData('prodnamethree') != ''):
        $cols = 2;
    endif;
?>

<section class="product-grid products grid col-<?php echo $cols; ?>">
    <?php if($block->getData('prodnameone') != ''): ?>
    <div class="item" style="background-image: url('<?php echo $block->getData('prodbgimageone'); ?>');">
        <h2><a href="<?php echo $block->getData('prodbuttonlinkone'); ?>"><?php echo $block->getData('prodnameone'); ?></a></h2>
        <h4><?php echo $block->getData('prodheadlineone'); ?></h4>
        <a href="<?php echo $block->getData('prodbuttonlinkone'); ?>"><img src="<?php echo $block->getData('prodimageone'); ?>" /></a>
        <div class="shop-cta">
            <a class="button" href="<?php echo $block->getData('prodbuttonlinkone'); ?>"><?php echo $block->getData('prodbuttontextone'); ?></a>
            <?php if($this->getData('pricetextone') != ''): ?>
            <aside><?php echo $block->getData('pricetextone'); ?></aside>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if($this->getData('prodnametwo') != ''): ?>
    <div class="item" style="background-image: url('<?php echo $block->getData('prodbgimagetwo'); ?>');">
        <h2><a href="<?php echo $block->getData('prodbuttonlinktwo'); ?>"><?php echo $block->getData('prodnametwo'); ?></a></h2>
        <h4><?php echo $block->getData('prodheadlinetwo'); ?></h4>
        <a href="<?php echo $block->getData('prodbuttonlinktwo'); ?>"><img src="<?php echo $block->getData('prodimagetwo'); ?>" /></a>
        <div class="shop-cta">
            <a class="button" href="<?php echo $block->getData('prodbuttonlinktwo'); ?>"><?php echo $block->getData('prodbuttontexttwo'); ?></a>
            <?php if($this->getData('pricetexttwo') != ''): ?>
            <aside><?php echo $block->getData('pricetexttwo'); ?></aside>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if($this->getData('prodnamethree') != ''): ?>
    <div class="item" style="background-image: url('<?php echo $block->getData('prodbgimagethree'); ?>');">
        <h2><a href="<?php echo $block->getData('prodbuttonlinkthree'); ?>"><?php echo $block->getData('prodnamethree'); ?></a></h2>
        <h4><?php echo $block->getData('prodheadlinethree'); ?></h4>
        <a href="<?php echo $block->getData('prodbuttonlinkthree'); ?>"><img src="<?php echo $block->getData('prodimagethree'); ?>" /></a>
        <div class="shop-cta">
            <a class="button" href="<?php echo $block->getData('prodbuttonlinkthree'); ?>"><?php echo $block->getData('prodbuttontextthree'); ?></a>
            <?php if($this->getData('pricetextthree') != ''): ?>
            <aside><?php echo $block->getData('pricetextthree'); ?></aside>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>
</section>
