<div
    class="sp-account-billing sp-max-w-xl lg:sp-mr-8"
    data-bind="scope: 'billingInformation'"
>
    <!-- ko template: "SMG_SubscriptionAccounts/billing-information.html" --><!-- /ko -->
</div>

<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "billingInformation": {
                        "component": "SMG_SubscriptionAccounts/js/billing-information",
                        "billing": <?php echo json_encode( $block->getBillingInformation() ); ?>,
                        "states": <?php echo json_encode( $block->getStates() ); ?>,
                        "countries": <?php echo json_encode( $block->getCountries() ); ?>,
                        "recurlyApi": "<?php echo $block->escapeHtml($block->getRecurlyPublicApiKey()); ?>"
                    }
                }
            }
        }
    }
</script>
