<?php
$iframeProductId = $this->getData('product_id');
$iframeSelectedProduct = $this->getData('selected_product');
$iframeChildProducts = $this->getData('child_products');
$iframeQuantity = $this->getData('quantity');
$iframeChildrenPrice = $this->getData('children_price');
$iframeBasePrice = $this->getData('base_price');
$iframeBaseProductId = $this->getData('base_product_id');
$iframeSku = $this->getData('sku');
$iframeDrupalProductId = $this->getData('drupalProductId');
$iframeDesktop = $this->getData('desktop');

$baseUrl = $block->getBaseUrl();
$url = $baseUrl . "iframes/addtocart/add";

$addToCarJS = $block->getViewFileUrl('SMG_Iframes::js/addToCart.js');
?>

<html>
<head>
  <title></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <!-- Quick and Dirty get jquery. todo: If time come back and find a way via requireJS     -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="<?php echo $this->escapeUrl($addToCarJS); ?>"></script>
</head>
<body class="system-m product--cta <? if ($this->escapeHtml($iframeDesktop)) { ?>desktop<? } ?>">

<div class="cta__container">

  <div class="cta__container--price">
            <span class="regular-price" id="product-price-13_clone">
              <?php if ($this->escapeHtml($iframeChildrenPrice)): ?>
                $<span id="list-price"><?php echo sprintf("%.02f", $this->escapeHtml($iframeChildrenPrice)); ?></span>
              <?php else: ?>
                $<span id="list-price"><?php echo sprintf("%.02f", $this->escapeHtml($iframeBasePrice)); ?></span>
              <?php endif; ?>
                <input type="hidden" id="base-product-id"
                       value=<?php echo '"' . $this->escapeHtml($iframeBaseProductId) . '"' ?>/>
            </span>
  </div>

  <div class="cta__container--options">
    <div class="block__item">
      <button type="button" title="Add to Cart" class="button button--cart" id="cart-add"
              data-size_id="<?php echo str_replace(' ', '', trim(strtolower($this->getData('size')))); ?>"
              data-sku_id="<?php echo $this->escapeHtml($iframeSku); ?>"
              data-drupal-sku="<? echo $this->escapeHtml($iframeDrupalProductId); ?>"
              data-magento-add-url="<? echo $this->escapeUrl($url); ?>">
        <span>Add to Cart</span>
      </button>
    </div><!-- .block__item -->

    <?php $child_products = $this->escapeHtml($iframeChildProducts); ?>

    <div class="block__item">
      <div class="block__subblock">
        <?php if (count($child_products) != 0 && !$this->escapeHtml($iframeChildrenPrice)): ?>
          <label class="block__subblock--label size-label" for="child-products">Size</label>
          <select name="product_id" id="child-products"
            <?php if ($this->escapeHtml($iframeChildrenPrice)): ?>
              data-price="<?php echo sprintf("%.02f", $this->escapeHtml($iframeChildrenPrice)); ?>"
            <?php endif; ?>
          >
            <?php foreach ($child_products as $prod): ?>
              <option value="<? echo $prod->getId(); ?>"
                <?php if ($this->escapeHtml($iframeSelectedProduct) == $prod->getId()): ?> selected<?php endif; ?>
                      data-price="<?php echo sprintf("%.02f", $prod->getPrice()); ?>"
                      data-size="<?php echo str_replace(' ', '', trim(strtolower($prod->getAttributeText('product_sizes')))); ?>"
                      data-sku="<?php echo $prod->getSku(); ?>"
                      data-drupal-sku="<?php echo $prod->getdrupalproductid(); ?>" >
                <?php echo $prod->getAttributeText('product_sizes'); ?>
              </option>
            <?php endforeach; ?>
          </select>
          <div class="product__select">
            <div name="product_id" id="size-options"
              <?php if ($this->escapeHtml($iframeChildrenPrice)): ?>
                data-price="<?php echo sprintf("%.02f", $this->escapeHtml($iframeChildrenPrice)); ?>"
              <?php endif; ?>
            >
              <?php foreach ($child_products as $prod): ?>
                <label for="465" data-price="">
                  <input type="radio"
                         name="size"
                         value="<? echo $prod->getId(); ?>"
                    <?php if ($this->escapeHtml($iframeSelectedProduct) == $prod->getId()): ?> checked<?php endif; ?>
                         data-price="<?php echo sprintf("%.02f", $prod->getPrice()); ?>"
                         data-size="<?php echo str_replace(' ', '', trim(strtolower($prod->getAttributeText('product_sizes')))); ?>"
                         data-sku="<?php echo $prod->getSku(); ?>"
                         data-drupal-sku="<? echo $prod->getdrupalproductid(); ?>" />
                  <span><?php echo $prod->getAttributeText('product_sizes'); ?></span>
                </label>
              <?php endforeach; ?>
            </div>
          </div>
        <?php endif; ?>
      </div>

      <div class="block__subblock">
        <label class="block__subblock--label" for="qty">Quantity</label>

        <label id="qty-wrap">
          <input type="text" pattern="\d*" name="quantity" id="qty" maxlength="12" value="1" title="Qty"
                 class="block__subblock--input" size="3"/>
          <button class="minus">-</button>
          <button class="plus">+</button>
        </label>
      </div>
    </div><!-- .block__item -->
  </div><!-- .atc__block -->
</div>
</body>
</html>
