<?php
$iFrameSkusById = $this->getData('skusById');
$iFrameDrupalIdsById = $this->getData('drupalIdsById');
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="cta__container">
    <div class="cta__container--options">
        <form data-skus-by-id='<?=$this->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($iFrameSkusById))?>'
              data-drupal-ids-by-id='<?=$this->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($iFrameDrupalIdsById))?>'
              id="product_addtocart_form"
              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
              action="<?= $block->escapeUrl($block->getSubmitUrl($_product)) ?>" method="post"
              id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <input type="hidden" name="product" value="<?= $this->escapeHtml($_product->getId()) ?>" />
            <input type="hidden" name="selected_configurable_option" value="" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
            <input type="hidden" name="item"  value="<?= $this->escapeHtml($block->getRequest()->getParam('id')) ?>" />
            <?= /* @NoEscape */$block->getBlockHtml('formkey') ?>
            <div class="block__item">

            </div><!-- .block__item -->
            <div class="block__item">
                <?php if ($_product->isSaleable() && $block->getChildHtml('options_configurable')):?>
                    <?= /* @NoEscape */$block->getChildHtml('options_configurable') ?>
                <?php endif;?>
            </div>

            <div class="block__item btn-qty-cols">
                <div class="button-container">
                    <button type="submit" title="Add to Cart" class="button button--cart" id="cart-add"
                            data-size_id="<?php echo $this->escapeHtml(str_replace(' ', '', trim(strtolower($_product->getData('size'))))); ?>"
                            data-sku_id="<?php echo $this->escapeHtml($_product->getData('sku')); ?>"
                            data-drupal-sku="<?php echo $this->escapeHtml($_product->getData('drupalproductid')); ?>">
                        <span>Add to Cart</span>
                    </button>
                </div>

                <div class="block__subblock">
                    <label class="block__subblock--label" for="qty">Quantity</label>

                    <label id="qty-wrap">
                        <input type="text" name="qty" id="qty" maxlength="12" value="1" title="Qty"
                               class="block__subblock--input" size="3"/>
                        <!-- Use special HTML character code so they have the same width -->
                        <button type="button" class="minus">&#8722;</button>
                        <button type="button" class="plus">&#43;</button>
                    </label>
                </div>
            </div><!-- .block__item -->
        </form>
    </div><!-- .cta__block -->
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?= $block->escapeHtml($_product->getId()) ?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>});
    });
</script>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        },
        "*" : {
            "SMG_Iframes/js/addToCart": {}
        }
    }
</script>

