<div class="nav__cart">
    <a id="cart-checkout" data-target-element="#header-cart" class="nav__cart--wrapper" target="_parent">
        <span class="nav__cart--icon"></span>
      <? if ($this->escapeHtml($this->getData('cartCount')) != 0 ) : ?>
          <span class="nav__cart--label">Cart <span class="count"><?php echo $this->escapeHtml($this->getData('cartCount')); ?></span></span>
          <span class="checkout-now">Checkout Now</span>
      <? endif; ?>
    </a>
</div>

<script type="text/javascript" src="<?php echo $block->getViewFileUrl('SMG_Iframes::js/cart.js'); ?>"></script>
