<?php $ajaxurl = $block->escapeurl( $block->getFormAction() ); ?>
<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "contactForm": {
						"component": "SMG_SPV2ContactWidget/js/contactajax",
						"AjaxUrl": "<?= $ajaxurl; ?>",
						"customerName": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>",
						"email": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>",
                        "phone": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('phone')) ?>",
					    "address": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('address')) ?>",
                        "address2": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('address2')) ?>",
					    "city": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('city')) ?>",
					    "postalCode": "<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('postalCode')) ?>",
					    "comment": "<?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?>"
					}
                }
            }
        }
    }
</script>
<div class="loader">
    <img src="<?= $block->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>"
         alt="$block->escapeHtmlAttr(__('Loading...')) ?>"
         style="position: absolute;">
</div>
<form
    id="contact-form"
    action="<?= $block->escapeUrl($block->getFormAction()) ?>"
    class="form contact"
    style="display: none"
    data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
    data-bind="scope: 'contactForm'"
    method="post"
>

    <fieldset class="fieldset">
        <div class="sp-form-group">
            <input
                class="input-text sp-input sp-w-full"
                data-bind="textInput: form.name"
                data-validate="{
                    required: false,
                    'validate-name': true
                }"
                id="name"
                name="name"
                maxLength="100"
                placeholder="<?= $block->escapeHtml(__('Name')) ?>*"
                title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                type="text"
            />
            <label class="label sp-form-label required" for="name"><?= $block->escapeHtml(__('Name')) ?>*</label>
        </div>

        <div class="sp-form-group">
            <input
                class="input-text sp-input sp-w-full"
                data-bind="textInput: form.email"
                data-validate="{
                    required: false,
                    'validate-email-address': true
                }"
                id="email"
                name="email"
                placeholder="<?= $block->escapeHtml(__('Email')) ?>*"
                title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                type="email"
            />
            <label class="label sp-form-label required" for="email"><?= $block->escapeHtml(__('Email')) ?>*</label>
        </div>
        <div class="sp-form-group">
            <div class="sp-select sp-w-full">
                <select name="topic" id="topic" class="sp-w-full"
                        data-bind="options: topics, value: form.topic, optionsCaption: '<?= $block->escapeHtml(__('Select a Topic')) ?>'"
                        data-validate="{
                    required: false,
                    'validate-select': true
                }">
                </select>
            </div>
            <label class="label sp-form-label required" for="topic"><?= $block->escapeHtml(__('Topic')) ?>*</label>
        </div>
        <div class="sp-form-group sp-mt-12">
            <textarea
                class="input-text sp-textarea sp-input sp-w-full"
                cols="5"
                data-bind="textInput: form.comment"
                data-validate="{
                    required: false,
                    'validate-message': true
                }"
                id="comment"
                name="comment"
                rows="3"
                title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"></textarea>
            <label class="label sp-form-label required" for="comment"><?= $block->escapeHtml(__('Message')) ?>*</label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible">
            <input
                    class="input-text sp-input sp-w-full"
                    data-validate="{required:true}"
                    id="address"
                    name="address"
                    maxLength="100"
                    placeholder="<?= $block->escapeHtml(__('Address')) ?>*"
                    title="<?= $block->escapeHtmlAttr(__('Address')) ?>"
                    type="text"
            />
            <label class="label sp-form-label required" for="address"><?= $block->escapeHtml(__('Address')) ?>*</label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible">
            <input
                    class="input-text sp-input sp-w-full"
                    data-validate="{required:false}"
                    id="address2"
                    name="address2"
                    maxLength="100"
                    placeholder="<?= $block->escapeHtml(__('Address2')) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Address2')) ?>"
                    type="text"
            />
            <label class="label sp-form-label" for="address2"><?= $block->escapeHtml(__('Address2')) ?></label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible">
            <input
                    class="input-text sp-input sp-w-full"
                    data-validate="{required:true}"
                    data-bind="textInput: form.city"
                    id="city"
                    name="city"
                    maxLength="100"
                    placeholder="<?= $block->escapeHtml(__('City')) ?>*"
                    title="<?= $block->escapeHtmlAttr(__('City')) ?>"
                    type="text"
            />
            <label class="label sp-form-label required" for="city"><?= $block->escapeHtml(__('City')) ?>*</label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible">
            <div class="sp-select sp-w-full">
                <select data-bind="options: states, value: form.state, optionsCaption: '<?= $block->escapeHtml(__('Select State')) ?>'"
                        name="state" id="state" class="sp-w-full" data-validate="{required: true}">
                </select>
            </div>
            <label class="label sp-form-label required" for="state"><?= $block->escapeHtml(__('State')) ?>*</label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible() || lawnInfoVisible()">
            <input
                    class="input-number sp-input sp-w-full"
                    data-validate="{ required:false, 'validate-postal-code': true }"
                    id="postalCode"
                    name="postalCode"
                    maxLength="5"
                    placeholder="<?= $block->escapeHtml(__('Postal Code')) ?>*"
                    title="<?= $block->escapeHtmlAttr(__('Postal Code')) ?>"
                    type="number"
            />
            <label class="label sp-form-label required" for="postalCode"><?= $block->escapeHtml(__('Postal Code')) ?>*</label>
        </div>
        <div class="sp-form-group" data-bind="visible: addressVisible">
            <input
                    class="input-number sp-input sp-w-full"
                    data-bind="textInput: form.phone"
                    data-validate="{required:true}"
                    id="phone"
                    name="phone"
                    maxLength="15"
                    placeholder="<?= $block->escapeHtml(__('Phone')) ?>"
                    title="<?= $block->escapeHtmlAttr(__('Phone')) ?>"
                    type="text"
            />
            <label class="label sp-form-label required" for="phone"><?= $block->escapeHtml(__('Phone')) ?></label>
        </div>
        <div class="sp-form-group" data-bind="visible: lawnInfoVisible">
            <div class="sp-select sp-w-full">
                <select data-bind="options: grassTypes, value: form.grassType, optionsCaption: '<?= $block->escapeHtml(__('Select Grass Type')) ?>'"
                        name="grassType" id="grassType" class="sp-w-full" data-validate="{required: false, 'validate-select': true}">
                </select>
            </div>
            <label class="label sp-form-label required" for="state"><?= $block->escapeHtml(__('Grass Type')) ?>*</label>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="sp-form-group actions-toolbar">
        <input type="hidden" name="hideit" id="hideit" value="" />
        <button data-bind="visible: !saving()" type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action sp-button sp-button--primary">
            <?= $block->escapeHtml(__('Send')) ?>
        </button>
        <button type="button"
                class="action sp-button sp-button--primary sp-button--inactive sp-button--loading"
                data-bind="visible: saving()"><?= $block->escapeHtml(__('Send')) ?>
        </button>
    </div>
</form>

<div id="popup-modal" style="display:none;">
    <h2 class="sp-h2 sp-text-black sp-text-center">Success!</h2>
    <div class="content">
        <p class="sp-text-lg sp-text-center">We’ll be in touch soon.</p>
    </div>
</div>


