<form class="form contact" action="<?= $block->escapeUrl($block->getFormAction()) ?>" id="contact-form" method="post" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="sp-form-group">
            <input
                class="input-text sp-input sp-w-full"
                data-validate="{
                    required: false,
                    'validate-name': true
                }"
                id="name"
                name="name"
                maxLength="100"
                placeholder="<?= $block->escapeHtml(__('Name')) ?>*"
                title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                type="text"
                value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
            />
            <label class="label sp-form-label required" for="name"><?= $block->escapeHtml(__('Name')) ?>*</label>
        </div>
        <div class="sp-form-group">
            <input
                class="input-text sp-input sp-w-full"
                data-validate="{
                    required: false,
                    'validate-email-address': true
                }"
                id="email"
                name="email"
                placeholder="<?= $block->escapeHtml(__('Email')) ?>*"
                title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                type="email"
                value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
            />
            <label class="label sp-form-label required" for="email"><?= $block->escapeHtml(__('Email')) ?>*</label>
        </div>
        <div class="sp-form-group">
            <div class="sp-select sp-w-full">
                <select name="topic" id="topic" class="sp-w-full" data-validate="{
                    required: false,
                    'validate-one-required': true
                }">
                    <option value="0" selected disabled style="display: none;">-- Choose --</option>
                    <option value="Information about products or my lawn care plan">Information about products or my lawn care plan</option>
                    <option value="Question or concern with my order">Question or concern with my order</option>
                    <option value="Canceling my subscription">Canceling my subscription</option>
                    <option value="Question or concern with the website or mobile app">Question or concern with the website or mobile app</option>
                    <option value="General question or commen">General question or comment</option>
                </select>
            </div>
            <label class="label sp-form-label required" for="topic"><?= $block->escapeHtml(__('Topic')) ?>*</label>
        </div>
        <div class="sp-form-group sp-mt-12">
            <textarea
                class="input-text sp-textarea sp-input sp-w-full"
                cols="5"
                data-validate="{
                    required: false,
                    'validate-message': true
                }"
                id="comment"
                name="comment"
                rows="3"
                title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
            ><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            <label class="label sp-form-label required" for="comment"><?= $block->escapeHtml(__('Message')) ?>*</label>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="sp-form-group actions-toolbar">
        <input type="hidden" name="hideit" id="hideit" value="" />
        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action sp-button sp-button--primary">
            <?= $block->escapeHtml(__('Send')) ?>
        </button>
    </div>
</form>

<div id="popup-modal" style="display:none;">
    <h2 class="sp-h2 sp-text-black sp-text-center">Success!</h2>
    <div class="content">
        <p class="sp-text-lg sp-text-center">We’ll be in touch soon.</p>
    </div>
</div>

<?php $ajaxurl = $block->escapeurl( $block->getFormAction() ); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "SMG_SPV2ContactWidget/js/contactajax": {
                "AjaxUrl": "<?php echo $ajaxurl; ?>"
            }
        }
    }
</script>
