<?php
//Declare vars to be used
$bg_class = '';
$customCssStyle = '';
$headlineCustomCssStyle = '';
$paragraphTextSize = '';
$selectedBannerTextImageOne = '';
$selectedBannerTextImageTwo = '';
$selectedBannerTextImgOneLink = '';
$selectedBannerTextImgTwoLink = '';
$selectedBlurbImgOneAltTxt = '';
$selectedBlurbImgTwoAltTxt = '';
$selectedBannerCalloutImageAltTxt = '';


// If textstyle exists then set to customCssStyles
if($block->getData('textstyle') != ''):
  $customCssStyle = $block->getData('textstyle');
endif;


//If headlinetextstyle exists then set to customCssStyles
if($block->getData('headlinetextstyle') != ''):
  $headlineCustomCssStyle = $block->getData('headlinetextstyle');
endif;


// If bgimage exists then set to bg_class
if($block->getData('bgimage') != ''):
  $bg_class = 'image-bg';
endif;


// If bannertextsize exists then set to paragraphTextSize
if($block->getData('bannertextsize') != ''):
  $paragraphTextSize = $block->getData('bannertextsize');
endif;


// Check for existence of bannerTextImgOne
if($block->getData('bannerTextImageOne') != ''):
  $selectedBannerTextImageOne = $block->getData('bannerTextImageOne');
endif;


// Check for existence of bannerTextImgTwo
if($block->getData('bannerTextImageTwo') !=''):
  $selectedBannerTextImageTwo = $block->getData('bannerTextImageTwo');
endif;


// Check for existence of bannerTextImgOneLink
if($block->getData('bannerTextImgOneLink') !=''):
  $selectedBannerTextImgOneLink = $block->getData('bannerTextImgOneLink');
endif;


// Check for existence of bannerTextImgTwoLink
if($block->getData('bannerTextImgTwoLink') !=''):
  $selectedBannerTextImgTwoLink = $block->getData('bannerTextImgTwoLink');
endif;


// Check existence of an alt txt for Blurb Img One
if($block->getData('blurbImgOneAltTxt') !=''):
  $selectedBlurbImgOneAltTxt = $block->getData('blurbImgOneAltTxt');
endif;


// Check existence of an alt txt for Blurb Img Two
if($block->getData('blurbImgTwoAltTxt') !=''):
  $selectedBlurbImgTwoAltTxt = $block->getData('blurbImgTwoAltTxt');
endif;


// Check existence of an alt txt for Callout Img
if($block->getData('bannerCalloutImageAltTxt') !=''):
  $selectedBannerCalloutImageAltTxt = $block->getData('bannerCalloutImageAltTxt');
endif;

?>

<section class="product-callout-widget product-info-container" style="<?php if ($this->getData('bgimage') != ''):
  ?>background: url('<?php echo $block->escapeUrl($block->getData('bgimage')); ?>') no-repeat; background-size:cover;background-position:center;<?php endif; ?><?php if ($this->getData('bgcolor') != ''):?>background-color:<?php echo $block->escapeHtmlAttr($block->getData('bgcolor')); ?>;<?php else: ?>background-color:transparent<?php endif;?>">
  <div class="product-info grid col-2">
    <?php if($this->getData('bannerimage') != ''): ?>
      <div class="productCallout-imageContainer span_6_of_12"> 
        <img src="<?php echo $block->escapeUrl($block->getData('bannerimage')); ?>" alt="<?php echo
        $block->escapeHtml($selectedBannerCalloutImageAltTxt);?>">
      </div>
    <?php endif; ?>

    <div class="productCallout-contentContainer span_6_of_12 <?php echo $block->escapeHtml($block->getData('textalignclass')); ?>">
      <h2 style="<?php $headlinestylevalues = explode(',', $headlineCustomCssStyle);
            foreach($headlinestylevalues as $headlinevalue) {
            echo  /* @noEscape */ $headlinevalue;
            } ?>color:<?php echo $block->escapeHtmlAttr($block->getData('bannerheadlinecolor')); ?>;"><?php echo /* @noEscape */ $block->escapeHtml($block->getData('bannerheadline')); ?></h2>
      <p style="<?php $stylevalues = explode(',', $customCssStyle);
          foreach($stylevalues as $value) {
            /* @noEscape */ echo $value;
          }echo /* @noEscape */ $block->escapeHtml($paragraphTextSize);?>color:<?php echo $block->escapeHtmlAttr($block->getData('bannertextlinecolor')); ?>;">
        <?php echo /* @noEscape */ $block->escapeHtml($block->getData('bannertext')); ?>
      </p>

      <!-- Check if link selected for Blurb Img One -->
      <?php if($selectedBannerTextImgOneLink != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageOne">
          <a href="<?php echo $block->escapeUrl($selectedBannerTextImgOneLink);?>" target="_blank" title="<?php echo
          $block->escapeHtml($selectedBlurbImgOneAltTxt);?>">
            <img src="<?php echo $block->escapeUrl($selectedBannerTextImageOne);?>" alt="<?php echo
            $block->escapeHtml($selectedBlurbImgOneAltTxt);?>">
          </a>
        </div>
          <!-- If no link then load just img -->
      <?php }elseif ($selectedBannerTextImageOne != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageOne">
          <img src="<?php echo $block->escapeUrl($selectedBannerTextImageOne);?>">
        </div>
      <?php }else{?>
        <!-- No One Img was selected -->
      <?php }?>


      <!-- Check if link selected for Blurb Img Two -->
      <?php if($selectedBannerTextImgTwoLink != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageTwo">
          <a href="<?php echo $block->escapeUrl($selectedBannerTextImgTwoLink);?>" target="_blank" title="<?php echo
          $block->escapeHtml($selectedBlurbImgTwoAltTxt);?>">
            <img src="<?php echo $block->escapeUrl($selectedBannerTextImageTwo);?>" alt="<?php echo
            $block->escapeHtml($selectedBlurbImgTwoAltTxt);?>">
          </a>
        </div>
        <!-- If no link then load just img -->
      <?php }elseif ($selectedBannerTextImageTwo != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageTwo">
          <img src="<?php echo $block->escapeUrl($selectedBannerTextImageTwo);?>">
        </div>
      <?php }else{?>
        <!-- No Two Img was selected -->
      <?php }?>

    </div>
  </div>
</section>
