<?php
//Declare vars to be used
$bg_class = '';
$customCssStyle = '';
$headlineCustomCssStyle = '';
$paragraphTextSize = '';
$selectedBannerTextImageOne = '';
$selectedBannerTextImageTwo = '';
$selectAltTextImageOne = '';
$selectAltTextImageTwo = '';
$selectedBannerTextImgOneLink = '';
$selectedBannerTextImgTwoLink = '';
$selectedBlurbImgOneAltTxt = '';
$selectedBlurbImgTwoAltTxt = '';


// If Check for existence of alttextimage1
if($block->getData('blurbImgOneAltText') != ''):
  $selectedBlurbImgOneAltTxt = $block->getData('blurbImgOneAltText');
endif;


//If Check for existence of alttextimage2
if($block->getData('blurbImgTwoAltText') != ''):
  $selectedBlurbImgTwoAltTxt = $block->getData('blurbImgTwoAltText');
endif;


// If textstyle exists then set to customCssStyles
if($block->getData('textstyle') != ''):
  $customCssStyle = $block->getData('textstyle');
endif;


//If headlinetextstyle exists then set to customCssStyles
if($block->getData('headlinetextstyle') != ''):
  $headlineCustomCssStyle = $block->getData('headlinetextstyle');
endif;


// If bgimage exists then set to bg_class
if($block->getData('bgimage') != ''):
  $bg_class = 'image-bg';
endif;


// If bannertextsize exists then set to paragraphTextSize
if($block->getData('bannertextsize') != ''):
  $paragraphTextSize = $block->getData('bannertextsize');
endif;


// Check for existence of bannerTextImgOne
if($block->getData('bannerTextImageOne') != ''):
  $selectedBannerTextImageOne = $block->getData('bannerTextImageOne');
endif;


// Check for existence of bannerTextImgTwo
if($block->getData('bannerTextImageTwo') !=''):
  $selectedBannerTextImageTwo = $block->getData('bannerTextImageTwo');
endif; 

// Check for existence of blurbImgOneLink
if($block->getData('blurbImgOneLink') !=''):
  $selectedBannerTextImgOneLink = $block->getData('blurbImgOneLink');
endif;


// Check for existence of blurbImgTwoLink
if($block->getData('blurbImgTwoLink') !=''):
  $selectedBannerTextImgTwoLink = $block->getData('blurbImgTwoLink');
endif;

?>



<section class="product-callout-widget product-info-container" style="background: url('<?php echo $block->getData('bgimage'); ?>') no-repeat; background-size:cover; background-position:center;
  background-color: <?php
echo
$block->getData('bgcolor');
?>; padding-top:5%; padding-bottom:5%;">
  <div class="product-info grid col-2">
    <?php if($this->getData('bannerimage') != ''): ?>
      <div class="productCallout-imageContainer span_6_of_12"> 
        <img src="<?php echo $block->getData('bannerimage'); ?>" blurb="<?php echo $block->getData('bannerCalloutImageAltTxt'); ?><?php //echo __('Image of MyLawn app from Scotts'); ?>">
      </div>
    <?php endif; ?>

    <div
      class="productCallout-contentContainer span_6_of_12 <?php echo $block->getData('textalignclass') ?>">
      <h2 style="<?php
          $headlinestylevalues = explode(',', $headlineCustomCssStyle);
            foreach($headlinestylevalues as $headlinevalue) {
            echo $headlinevalue;
            } ?>
        color:<?php echo $block->getData('bannerheadlinecolor'); ?>;">
          <?php echo $block->getData('bannerheadline'); ?>
      </h2>
      <p style="<?php
          //If selected display Font Styles
          $stylevalues = explode(',', $customCssStyle);
          foreach($stylevalues as $value) {
            echo $value;
          }

          //If selected display font size
          echo $paragraphTextSize;
        ?>
        color:<?php echo $block->getData('bannertextlinecolor'); ?>;">
        <?php echo strip_tags($block->getData('bannertext')); ?>
      </p>


      <!-- Check if link selected for Blurb Img One -->
      <?php if($selectedBannerTextImgOneLink != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageOne">
          <a href="<?php echo $selectedBannerTextImgOneLink; ?>" target="_blank" title="<?php echo $selectedBlurbImgOneAltTxt; ?>">
            <img src="<?php echo $selectedBannerTextImageOne; ?>" blurb="<?php echo $selectedBlurbImgOneAltTxt; ?>">
          </a>
        </div>
      <?php }elseif ($selectedBannerTextImageOne != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageOne">
          <img src="<?php echo $selectedBannerTextImageOne; ?>">
        </div>
      <?php }else{?>
        <!-- No One Img was selected -->
      <?php }?>


      <!-- Check if link selected for Blurb Img Two -->
      <?php if($selectedBannerTextImgTwoLink != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageTwo">
          <a href="<?php echo $selectedBannerTextImgTwoLink; ?>" target="_blank" title="<?php echo $selectedBlurbImgTwoAltTxt; ?>">
            <img src="<?php echo $selectedBannerTextImageTwo; ?>" blurb="<?php echo $selectedBlurbImgTwoAltTxt; ?>">
          </a>
        </div>
      <?php }elseif ($selectedBannerTextImageTwo != ''){?>
        <div class="selected-bannerTextImage selected-bannerTextImageTwo">
          <img src="<?php echo $selectedBannerTextImageTwo?>">
        </div>
      <?php }else{?>
        <!-- No Two Img was selected -->
      <?php }?>

    </div>
  </div>
</section>
