<?php

//Declaring Vars
$HeroCalloutBannerHeadlineCustomSize = '';
$HeroCalloutBannerTextCustomSize = '';
$HeroCalloutBannerTextHighlightCustomSize = '';
$HeroCalloutButtonTextCustomSize = '';
$HeroCalloutBannerHeadlineCustomColor = '';
$HeroCalloutBannerTextCustomColor = '';
$HeroCalloutBannerTextHighlightCustomColor = '';
$HeroCalloutButtonTextCustomColor = '';
$HeroCalloutButtonCustomColor = '';
$HeroCalloutBannerTextHighlightCustomStyle = '';
$HeroCalloutBannerHeadlineCustomStyles = '';
$HeroCalloutBannerTextCustomStyle = '';



//If HeroCalloutBannerHeadlineSize exists then set to $HeroCalloutBannerHeadlineCustomSize
if($block->getData('HeroCalloutBannerHeadlineSize') != ''):
  $HeroCalloutBannerHeadlineCustomSize = $block->getData('HeroCalloutBannerHeadlineSize');
endif;


//If HeroCalloutBannerTextSize exists then set to $HeroCalloutBannerTextCustomSize
if($block->getData('HeroCalloutBannerTextSize') != ''):
  $HeroCalloutBannerTextCustomSize = $block->getData('HeroCalloutBannerTextSize');
endif;


//If HeroCalloutBannerTextHighlightSize exists then set to $HeroCalloutBannerTextCustomSize
if($block->getData('HeroCalloutBannerTextHighlightSize') != ''):
  $HeroCalloutBannerTextHighlightCustomSize = $block->getData('HeroCalloutBannerTextHighlightSize');
endif;


//If HeroCalloutButtonTextSize exists then set to $HeroCalloutButtonTextCustomSize
if($block->getData('HeroCalloutButtonTextSize') != ''):
  $HeroCalloutButtonTextCustomSize = $block->getData('HeroCalloutButtonTextSize');
endif;


//If HeroCalloutBannerHeadlineColor exists then set to $HeroCalloutBannerHeadlineCustomColor
if($block->getData('HeroCalloutBannerHeadlineColor') != ''):
  $HeroCalloutBannerHeadlineCustomColor = $block->getData('HeroCalloutBannerHeadlineColor');
endif;


//If HeroCalloutBannerTextColor exists then set to $HeroCalloutBannerTextCustomColor
if($block->getData('HeroCalloutBannerTextColor') != ''):
  $HeroCalloutBannerTextCustomColor = $block->getData('HeroCalloutBannerTextColor');
endif;


//If HeroCalloutBannerTextHighlightColor exists then set to $HeroCalloutBannerTextHighlightCustomColor
if($block->getData('HeroCalloutBannerTextHighlightColor') != ''):
  $HeroCalloutBannerTextHighlightCustomColor = $block->getData('HeroCalloutBannerTextHighlightColor');
endif;


//If HeroCalloutButtonTextColor exists then set to $HeroCalloutButtonTextCustomColor
if($block->getData('HeroCalloutButtonTextColor') != ''):
  $HeroCalloutButtonTextCustomColor = $block->getData('HeroCalloutButtonTextColor');
endif;


//If HeroCalloutButtonColor exists then set to $HeroCalloutButtonCustomColor
if($block->getData('HeroCalloutButtonColor') != ''):
  $HeroCalloutButtonCustomColor = $block->getData('HeroCalloutButtonColor');
endif;


//If value exists for HeroCalloutBannerHeadlineStyles pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerHeadlineStyles') != ''):
  $HeroCalloutBannerHeadlineCustomStyles = str_replace(',' , '', $block->getData('HeroCalloutBannerHeadlineStyles'));
endif;


//If value exists for HeroCalloutBannerTextStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerTextStyle') != ''):
  $HeroCalloutBannerTextCustomStyle = str_replace(',' , '', $block->getData('HeroCalloutBannerTextStyle'));
endif;


//If value exists for HeroCalloutBannerTextHighlightStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerTextHighlightStyle') != ''):
  $HeroCalloutBannerTextHighlightCustomStyle = str_replace(',' , '', $block->getData
  ('HeroCalloutBannerTextHighlightStyle'));
endif;


//If value exists for HeroCalloutButtonTextStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutButtonTextStyle') != ''):
  $HeroCalloutButtonTextCustomStyle = str_replace(',' , '', $block->getData
  ('HeroCalloutButtonTextStyle'));
endif;

?>


<section class="connect-home col-2 span_12_of_12">
    <div class="content">
        <h2 style="<?php echo $HeroCalloutBannerHeadlineCustomSize?> color:<?php echo $HeroCalloutBannerHeadlineCustomColor?>; <?php echo $HeroCalloutBannerHeadlineCustomStyles?>"><?php echo $block->getData('bannerheadline'); ?></h2>
        <p style="<?php echo $HeroCalloutBannerTextCustomSize?> color:<?php echo $HeroCalloutBannerTextCustomColor?>; <?php echo $HeroCalloutBannerTextCustomStyle?>"><?php echo $block->getData
        ('bannertext'); ?></p>
        <p class="highlight" style="<?php echo $HeroCalloutBannerTextHighlightCustomSize?> color:<?php echo $HeroCalloutBannerTextHighlightCustomColor?>; <?php echo $HeroCalloutBannerTextHighlightCustomStyle?>"><?php echo $block->getData('bannertexthighlight'); ?></p>

        <?php if($block->getData('buttontext')): ?>
        <a class="button" style="<?php echo $HeroCalloutButtonTextCustomSize?> color:<?php echo $HeroCalloutButtonTextCustomColor?>; background:<?php echo $HeroCalloutButtonCustomColor?>; <?php echo $HeroCalloutButtonTextCustomStyle?>" href="<?php echo $block->getData('buttonlink'); ?>"><?php echo $block->getData('buttontext'); ?></a>
        <?php endif; ?>
    </div>
</section>

<style type="text/css">
    <?php if($this->getData('bannerimagemobile') != ''): ?>
    .connect-home {
        background-image: url('<?php echo $block->getData('bannerimagemobile'); ?>');
    }
    <?php endif; ?>

    <?php if($this->getData('bannerimage') != ''): ?>
    @media screen and (min-width: 1024px) {
        .connect-home {
            background-image: url('<?php echo $block->getData('bannerimage'); ?>');
        }
    }
    <?php endif; ?>
</style>
