<?php

//Declaring Vars
$HeroCalloutBannerHeadlineCustomSize = '';
$HeroCalloutBannerTextCustomSize = '';
$HeroCalloutBannerTextHighlightCustomSize = '';
$HeroCalloutButtonTextCustomSize = '';
$HeroCalloutBannerHeadlineCustomColor = '';
$HeroCalloutBannerTextCustomColor = '';
$HeroCalloutBannerTextHighlightCustomColor = '';
$HeroCalloutButtonTextCustomColor = '';
$HeroCalloutButtonCustomColor = '';
$HeroCalloutBannerTextHighlightCustomStyle = '';
$HeroCalloutBannerHeadlineCustomStyles = '';
$HeroCalloutBannerTextCustomStyle = '';
$HeroCalloutButtonTextCustomStyle = '';
$selectedButtonlink = '';
$selectedHeroCalloutButtonHoverColor = '';
$selectedBlurbMobileTextColor = '';
$selectedHeadlineMobileColor = '';


//If blurbMobileTextColor exists then set to variable
if($block->getData('blurbMobileTextColor') != ''):
  $selectedBlurbMobileTextColor = $block->getData('blurbMobileTextColor');
endif;


//If headlineMobileColor exists then set to variable
if($block->getData('headlineMobileColor') != ''):
  $selectedHeadlineMobileColor = $block->getData('headlineMobileColor');
endif;


//If buttonlink exists then set to variable
if($block->getData('buttonlink') != ''):
  $selectedButtonlink = $block->getData('buttonlink');
endif;


//If buttonlink exists then set to variable
if($block->getData('HeroCalloutButtonHoverColor') != ''):
  $selectedHeroCalloutButtonHoverColor = $block->getData('HeroCalloutButtonHoverColor');
endif;


//If HeroCalloutBannerHeadlineSize exists then set to variable
if($block->getData('HeroCalloutBannerHeadlineSize') != ''):
  $HeroCalloutBannerHeadlineCustomSize = $block->getData('HeroCalloutBannerHeadlineSize');
endif;


//If HeroCalloutBannerTextSize exists then set to variable
if($block->getData('HeroCalloutBannerTextSize') != ''):
  $HeroCalloutBannerTextCustomSize = $block->getData('HeroCalloutBannerTextSize');
endif;


//If HeroCalloutBannerTextHighlightSize exists then set to variable
if($block->getData('HeroCalloutBannerTextHighlightSize') != ''):
  $HeroCalloutBannerTextHighlightCustomSize = $block->getData('HeroCalloutBannerTextHighlightSize');
endif;


//If HeroCalloutButtonTextSize exists then set to variable
if($block->getData('HeroCalloutButtonTextSize') != ''):
  $HeroCalloutButtonTextCustomSize = $block->getData('HeroCalloutButtonTextSize');
endif;


//If HeroCalloutBannerHeadlineColor exists then set to variable
if($block->getData('HeroCalloutBannerHeadlineColor') != ''):
  $HeroCalloutBannerHeadlineCustomColor = $block->getData('HeroCalloutBannerHeadlineColor');
endif;


//If HeroCalloutBannerTextColor exists then set to variable
if($block->getData('HeroCalloutBannerTextColor') != ''):
  $HeroCalloutBannerTextCustomColor = $block->getData('HeroCalloutBannerTextColor');
endif;


//If HeroCalloutBannerTextHighlightColor exists then set to variable
if($block->getData('HeroCalloutBannerTextHighlightColor') != ''):
  $HeroCalloutBannerTextHighlightCustomColor = $block->getData('HeroCalloutBannerTextHighlightColor');
endif;


//If HeroCalloutButtonTextColor exists then set to variable
if($block->getData('HeroCalloutButtonTextColor') != ''):
  $HeroCalloutButtonTextCustomColor = $block->getData('HeroCalloutButtonTextColor');
endif;


//If HeroCalloutButtonColor exists then set to variable
if($block->getData('HeroCalloutButtonColor') != ''):
  $HeroCalloutButtonCustomColor = $block->getData('HeroCalloutButtonColor');
endif;


//If value exists for HeroCalloutBannerHeadlineStyles pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerHeadlineStyles') != ''):
  $HeroCalloutBannerHeadlineCustomStyles = str_replace(',' , '', $block->getData('HeroCalloutBannerHeadlineStyles'));
endif;


//If value exists for HeroCalloutBannerTextStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerTextStyle') != ''):
  $HeroCalloutBannerTextCustomStyle = str_replace(',' , '', $block->getData('HeroCalloutBannerTextStyle'));
endif;


//If value exists for HeroCalloutBannerTextHighlightStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutBannerTextHighlightStyle') != ''):
  $HeroCalloutBannerTextHighlightCustomStyle = str_replace(',' , '', $block->getData
  ('HeroCalloutBannerTextHighlightStyle'));
endif;


//If value exists for HeroCalloutButtonTextStyle pull in the value and replace the comma for a space
if($block->getData('HeroCalloutButtonTextStyle') != ''):
  $HeroCalloutButtonTextCustomStyle = str_replace(',' , '', $block->getData
  ('HeroCalloutButtonTextStyle'));
endif;

?>


<!-- Setting CMS Value of Hover Color -->
<style>
    .hero-callout button:hover {
        background-color:<? echo $selectedHeroCalloutButtonHoverColor?> !important;
    }
</style>

<section class="hero-callout col-2 span_12_of_12">
    <div class="content">
        <h2 style="<?php echo $block->escapeHtmlAttr($HeroCalloutBannerHeadlineCustomSize);?> color:<?php echo
        $block->escapeHtmlAttr($HeroCalloutBannerHeadlineCustomColor);?>; <?php echo $block->escapeHtmlAttr($HeroCalloutBannerHeadlineCustomStyles);?>">
          <?php echo $block->escapeHtml($block->getData('bannerheadline')); ?>
        </h2>

        <?php if($block->getData('bannertext') != ''): ?>
            <div class="heroCallout-bannerText" style="<?php echo $block->escapeHtmlAttr
            ($HeroCalloutBannerTextCustomSize);?> color:<?php echo $block->escapeHtmlAttr
            ($HeroCalloutBannerTextCustomColor);?>;">
                <!-- Load WYSIWYG Content -->
                <?php echo /* @noEscape */ $block->getData('bannertext'); ?>
            </div>
        <?php endif; ?>

        <?php if($block->getData('bannertexthighlight') != ''): ?>
            <div class="heroCallout-bannerTextHighlight" style="<?php echo
            $block->escapeHtmlAttr($HeroCalloutBannerTextHighlightCustomSize);?> color:<?php echo
            $block->escapeHtmlAttr($HeroCalloutBannerTextHighlightCustomColor);?>;">
                <?php echo /* @noEscape */ $block->getData('bannertexthighlight'); ?>
            </div>
        <?php endif; ?>

        <?php if($block->getData('buttontext')): ?>
        <button style="<?php echo $block->escapeHtmlAttr($HeroCalloutButtonTextCustomSize);?> color:<?php echo
        $block->escapeHtmlAttr($HeroCalloutButtonTextCustomColor);?>; background:<?php echo $block->escapeHtmlAttr
        ($HeroCalloutButtonCustomColor);?>; <?php echo
        $HeroCalloutButtonTextCustomStyle?>" onclick="window.location='<? echo $selectedButtonlink?>';"><?php echo
          $block->getData('buttontext'); ?></button>
        <?php endif; ?>
    </div>
</section>

<style type="text/css">
    @media screen and (max-width: 1024px) {
        .hero-callout .content h2 {
            color: <?php echo $selectedHeadlineMobileColor?> !important;
        }
        .hero-callout .content .heroCallout-bannerText{
            color: <?php echo $selectedBlurbMobileTextColor?> !important;
        }
    }
    <?php if($this->getData('bannerimagemobile') != ''): ?>
    .hero-callout {
        background-image: url('<?php echo $block->getData('bannerimagemobile'); ?>');
    }
    <?php endif; ?>

    <?php if($this->getData('bannerimage') != ''): ?>
    @media screen and (min-width: 1024px) {
        .hero-callout {
            background-image: url('<?php echo $block->getData('bannerimage'); ?>');
        }
    }
    <?php endif; ?>
</style>
