<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
  <div class="box-tocart">
    <div class="fieldset">
      <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
          <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
          <div class="control">
            <input type="number"
                   name="qty"
                   id="qty"
                   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                   class="input-text qty"
                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
            />
          </div>
        </div>
      <?php endif; ?>
      <div class="actions">
        <button type="submit"
                title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                class="action primary tocart"
                id="product-addtocart-button">
          <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
        </button>
        <?= $block->getChildHtml('', true) ?>
      </div>
    </div>
  </div>
<?php endif; ?>


<!-- Product Quick Info -->
<div class="product-quickInfo" id="sensors-quickInfo">
    <div class="quickInfo-item">
        <img src="images/quickInfo-cloud.png">
        <span>For indoor and outdoor plants</span>
    </div>
    <div class="quickInfo-item">
        <img src="">
        <span>Easy to<br>setup</span>
    </div>
    <div class="quickInfo-item">
        <img src="">
        <span>Managed from your phone</span>
    </div>
</div>
<div class="product-quickInfo" id="controllers-quickInfo">
    <div class="quickInfo-item">
        <img src="">
        <span>Uses local weather data</span>
    </div>
    <div class="quickInfo-item">
        <img src="">
        <span>Easy to<br>install</span>
    </div>
    <div class="quickInfo-item">
        <img src="">
        <span>Connect to your phone</span>
    </div>
</div>


<!-- Calling JS -->
<script type="text/x-magento-init">

{
    "*": {
        "Magento_Catalog/js/product-quick-info": {}
    }
}
</script>
