<div class="gigya-screen-content gigya-locale-en">
	<div class="gigya-screen-content gigya-screen landscape after-gigya-landscape">
		<div class="gigya-layout-row">
			<div class="gigya-layout-cell responsive under-site-login">
				<div class="after-gigya-login" style="display: none;">
					<p class="sp-text-sm">For questions, email us at  scotts-orders@scotts.com or call us at 1-877-220-3091</p>
				</div>
				<div class="after-gigya-register" style="display: none;">
					<p class="sp-text-sm">By subscribing, I agree to the <a href="https://scottsmiraclegro.com/terms-conditions
	" target="_blank">Conditions of Use</a>, including the provisions for <a href="https://scottsmiraclegro.com/terms-conditions//#arbitration_waiver
	" target="_blank">arbitration and class action waiver</a>. See our <a href="https://scottsmiraclegro.com/privacy
	" target="_blank">Privacy Notice</a> for what <a href="https://scottsmiraclegro.com/privacy/#3_info_we_collect
	" target="_blank">information we collect</a> and <a href="https://scottsmiraclegro.com/privacy/#16_your_rights
	" target="_blank">your rights</a>.</p>
					<p class="sp-text-sm">*By opting in, you are signing up to receive emails marketed by Scotts Miracle-Gro, its affiliates, and select partners with related tips, information, and promotions.</p>
				</div>
			</div>
		</div>
	</div>
</div>