<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div class="custom-checkout-nav-btns">
        <div class="actions backbtn">
            <a class="action back" href="<?= $block->escapeUrl($block->getUrl('checkout/cart/')) ?>" title="<?= $block->escapeHtmlAttr(__('Back to Cart')) ?>">
                <span><?= $block->escapeHtml(__('Back to Cart')) ?></span>
            </a>
        </div>
    </div>
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>" alt="$block->escapeHtmlAttr(__('Loading...')) ?>" style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            },
            "*": {
                "Magento_Checkout/custom": {},
                "Magento_Checkout/js/view/coupon-field-validation": {}
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeHtmlAttr($block->getViewFileUrl('images/loader-1.gif')) ?>");
            return url.setBaseUrl('<?= $block->escapeHtmlAttr($block->getBaseUrl()) ?>');
        })
    </script>
</div>