<?php
const IGNORED_CATEGORY='All Products';
function getCategoryTree($currentCategory){
    $tree=[];
    $initialLevel=$currentCategory->getLevel();
    $level=$currentCategory->getLevel();
    if($level>2){
        $category=$currentCategory;
        while($level>1){
            $tree[$level]=$category->getName();
            $category=$category->getParentCategory();
            $level--;
        }
    }
    else if($level>1){
        $tree[$level]=$currentCategory->getName();

    }
    if($tree['2']==IGNORED_CATEGORY){
        $newTree=[];
        for($level=2;$level<$initialLevel;$level++){
            $newTree[$level]=$tree[strval($level+1)];
        }
        return $newTree;
    }
    return $tree;
}
$objectManager=\Magento\Framework\App\ObjectManager::getInstance();
$config=$objectManager->create('Freshrelevance\Digitaldatalayer\Helper\Config');
$isDdlEnabled = $config->getEnabledDdl();
$catTree=false;
$ddlData = null;
if($isDdlEnabled) {
    try {
        if($objectManager->get('Magento\Framework\Registry')->registry('current_category')) {
            $catTree = getCategoryTree($objectManager->get('Magento\Framework\Registry')->registry('current_category'));
        }
        $helper = $objectManager->create('Freshrelevance\Digitaldatalayer\Helper\Data');
        $ddlData = $helper->getDdlProductCollectionData($block, $catTree, false);
    } catch (Exception $e) {}
}
?>
<?php if($isDdlEnabled):?>
<script type="text/javascript">
    (function () {
        window.digitalData = (<?php echo $ddlData?$ddlData:'{}';?>);
    })();
</script>
<?php endif;?>
<!-- You have successfully installed the W3C Digital Data Layer Extension by Fresh Relevance.
With Fresh Relevance, you can create effortless personalization, live email content and cart and browse abandonment emails.
If you want to know more about us, then check us out at http://www.freshrelevance.com
If you need help with the extension, go to http://www.freshrelevance.com/contact -->
