<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Sales\Block\Adminhtml\Order\View\Info $block
 */

// @codingStandardsIgnoreFile

$order = $block->getOrder();
$orderAdd = $block->getOrderInfo();
$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);

$orderStoreDate = $block->formatDate(
    $order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($order->getStore())
);

$customerUrl = $block->getCustomerViewUrl();
$allowedAddressHtmlTags = ['b', 'br', 'em', 'i', 'li', 'ol', 'p', 'strong', 'sub', 'sup', 'ul'];
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php $confirmationEmailStatusMessage = $order->getEmailSent() ? __('The order confirmation email was sent') : __('The order confirmation email is not sent'); ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?> (<span><?= $block->escapeHtml($confirmationEmailStatusMessage) ?></span>)
                    <?php else: ?>
                        <a href="<?= $block->escapeHtml($block->getViewUrl($order->getId())) ?>"><?= $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></a>
                        <span>(<?= $block->escapeHtml($confirmationEmailStatusMessage) ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Order Date')) ?></th>
                    <td><?= $block->escapeHtml($orderAdminDate) ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Order Date (%1)', $block->getTimezoneForStore($order->getStore()))) ?></th>
                        <td><?= $block->escapeHtml($orderStoreDate) ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?= $block->escapeHtml(__('Order Status')) ?></th>
                    <td><span id="order_status"><?= $block->escapeHtml($order->getStatusLabel()) ?></span></td>
                </tr>
                <?= $block->getChildHtml() ?>
                <?php if ($block->isSingleStoreMode() == false):?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Purchased From')) ?></th>
                        <td><?= $block->escapeHtml($block->getOrderStoreName(), ['br']) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationChildId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the New Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeHtml($block->getViewUrl($order->getRelationChildId())) ?>">
                                <?= $block->escapeHtml($order->getRelationChildRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRelationParentId()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                        <td>
                            <a href="<?= $block->escapeHtml($block->getViewUrl($order->getRelationParentId())) ?>">
                                <?= $block->escapeHtml($order->getRelationParentRealId()) ?>
                            </a>
                        </td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Placed from IP')) ?></th>
                        <td><?= $block->escapeHtml($order->getRemoteIp()); echo $order->getXForwardedFor() ? ' (' . $block->escapeHtml($order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getGlobalCurrencyCode() != $order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getGlobalCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToGlobalRate()) ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                        <td><?= $block->escapeHtml($order->getBaseToOrderRate()) ?></td>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions">
                    <?php if ($customerUrl) : ?>
                        <a href="<?= /* @noEscape */ $customerUrl ?>" target="_blank">
                            <?= $block->escapeHtml(__('Edit Customer')) ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($customerUrl): ?>
                                <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                                    <span><?= $block->escapeHtml($order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?= $block->escapeHtml($order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?= $block->escapeHtml($groupName) ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?= $block->escapeHtml($data['label']) ?></th>
                            <td><?= $block->escapeHtml($data['value'], ['br']) ?></td>
                        </tr>
                    <?php endforeach;?>
                    <?= $block->getChildHtml('extra_customer_info') ?>
                </table>
            </div>
        </div>
    </div>
</section>

<?php
 if(!empty($orderAdd)){ 
 $additional_information = json_decode($orderAdd['additional_information']);
?>
<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('SMG Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Order #')) ?></th>
                        <td><?= $block->escapeHtml(__('%1', $orderAdd['order_id'])) ?></td>
                    </tr>
                   <tr>
                        <th><?= $block->escapeHtml(__('SAP Order #')) ?></th>
                        <td><?php if(!empty($orderAdd['sap_order_id'])) echo $block->escapeHtml(__($orderAdd['sap_order_id'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Sent to SAP')) ?></th>
                        <td id="order-sent"><?php if(!empty($orderAdd['order_sent'])) echo $block->escapeHtml(__($orderAdd['order_sent'])) ?></td>
                    </tr>
                    <?php
                     if(!empty($orderAdd['order_sent_date']))
                     {
                    ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Sent to SAP Date')) ?></th>
                        <td><?php echo $block->escapeHtml(__($orderAdd['order_sent_date'])) ?></td>
                    </tr>
                    <?php
                     }
                    ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Order Status')) ?></th>
                        <td><?php if(!empty($orderAdd['order_status'])) echo $block->escapeHtml(__($orderAdd['order_status'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Invoice #')) ?></th>
                        <td>
                            <ul class="smg_additional_details">
                            <?php
                                if(!empty($orderAdd['sap_billing_doc_number']))
                                {
                                    $invoices = explode(",", $orderAdd['sap_billing_doc_number']);

                                    // loop through the invoices
                                    foreach ($invoices as $invoice)
                                    {
                            ?>
                            <li><?php echo $block->escapeHtml(__($invoice)); ?></li>
                            <?php
                                    }
                                }
                            ?>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Fulfillment Locations')) ?></th>
                        <td>
                            <ul class="smg_additional_details">
                                <?php
                                if(!empty($orderAdd['fulfillment_location']))
                                {
                                    $fulfillmentLocations = explode(",", $orderAdd['fulfillment_location']);

                                    // loop through the invoices
                                    foreach ($fulfillmentLocations as $fulfillmentLocation)
                                    {
                                        ?>
                                        <li><?php echo $block->escapeHtml(__($fulfillmentLocation)); ?></li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Last 4')) ?></th>
                        <td><?php if(!empty($additional_information->{'last_four'})) echo $block->escapeHtml(__($additional_information->{'last_four'})) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('CC Authorization Transaction #')) ?></th>
                       <td><?php if(!empty($orderAdd['cc_authorization_transaction'])) echo $block->escapeHtml(__($orderAdd['cc_authorization_transaction'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('CC Capture Transaction #')) ?></th>
                        <td><?php if(!empty($orderAdd['cc_capture_transaction'])) echo $block->escapeHtml(__($orderAdd['cc_capture_transaction'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('CC Response')) ?></th>
                        <td><?php if(!empty($orderAdd['cc_response'])) echo $block->escapeHtml(__($orderAdd['cc_response'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('Shipping Description')) ?></th>
                        <td><?php if(!empty($orderAdd['shipping_description'])) echo $block->escapeHtml(__($orderAdd['shipping_description'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Shipping Code')) ?></th>
                        <td><?php if(!empty($orderAdd['sap_shipping_code'])) echo $block->escapeHtml(__($orderAdd['sap_shipping_code'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Tracking #')) ?></th>
                        <td>
                            <ul class="smg_additional_details">
                                <?php
                                if(!empty($orderAdd['tracking']))
                                {
                                    $trackingNumbers = explode(",", $orderAdd['tracking']);

                                    // loop through the invoices
                                    foreach ($trackingNumbers as $trackingNumber)
                                    {
                                        ?>
                                        <li><a href="<?php echo "https://www.fedex.com/apps/fedextrack/index.html?trackingnumber=" . $block->escapeHtml(__($trackingNumber)); ?>" target="_Blank"><?php echo $block->escapeHtml($trackingNumber); ?></a></li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Delivery Number')) ?></th>
                        <td>
                            <ul class="smg_additional_details">
                                <?php
                                if(!empty($orderAdd['delivery_number']))
                                {
                                    $deliveryNumbers = explode(",", $orderAdd['delivery_number']);

                                    // loop through the invoices
                                    foreach ($deliveryNumbers as $deliveryNumber)
                                    {
                                        ?>
                                        <li><?php echo $block->escapeHtml(__($deliveryNumber)); ?></li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </td>
                    </tr>
                    <?php if(!empty($orderAdd['subscription_order_id'])) { ?>
                    <tr>
                        <th><?= $block->escapeHtml(__('Subscription Order Id')) ?></th>
                        <td><?php if(!empty($orderAdd['subscription_order_id'])) echo $block->escapeHtml(__($orderAdd['subscription_order_id'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Subscription Type')) ?></th>
                        <td><?php if(!empty($orderAdd['subscription_type'])) echo $block->escapeHtml(__($orderAdd['subscription_type'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Subscription Ship Start')) ?></th>
                        <td><?php if(!empty($orderAdd['subscription_ship_start'])) echo $block->escapeHtml(__($orderAdd['subscription_ship_start'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Subscription Ship End')) ?></th>
                        <td><?php if(!empty($orderAdd['subscription_ship_end'])) echo $block->escapeHtml(__($orderAdd['subscription_ship_end'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Scotts Customer ID')) ?></th>
                        <td><?php if(!empty($orderAdd['scotts_customer_id'])) echo $block->escapeHtml(__($orderAdd['scotts_customer_id'])) ?></td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
    </div>
</section>
<?php } ?>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getBillingAddress()), $allowedAddressHtmlTags); ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= $block->escapeHtml(__('Shipping Address')) ?></span>
                    <div class="actions"><?= /* @noEscape */ $block->getAddressEditLink($order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?= $block->escapeHtml($block->getFormattedAddress($order->getShippingAddress()), $allowedAddressHtmlTags); ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>
