<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var \Magento\Framework\View\Element\Template $block */
?>
<?= $block->escapeHtml(__(
    'You added %1 - (%2 Bags Total) to your <a href="%3">shopping cart</a>.',
    $block->getData('product_name'),
    $block->getData('quantity'),
    $block->getData('cart_url')
), ['a']);
