<?php
    $items = array("itemone", "itemtwo", "itemthree", "itemfour", "itemfive", "itemsix", "itemseven", "itemeight", "itemnine", "itemten");

    $item_icons = array("itemiconone", "itemicontwo", "itemiconthree", "itemiconfour", "itemiconfive", "itemiconsix", "itemiconseven", "itemiconeight", "itemiconnine", "itemiconten");

    $selectedItemTextContainerPadding = '';

    $selectedItemTextSize = '';

    $selectedItemTextStyle = '';

    $selectedHeadlineBannerStyle = '';


    //If itemTextSize exists then set to $selectedItemTextSize
    if ($block->getData('itemTextSize') != ''):
        $selectedItemTextSize = $block->getData('itemTextSize');
    endif;


    //If itemTextContainerPadding exists then set to selectedItemTextContainerPadding
    if ($block->getData('itemTextContainerPadding') != ''):
        $selectedItemTextContainerPadding = $block->getData('itemTextContainerPadding');
    endif;


    //If value exists for itemTextStyle pull in the value and replace the comma for a space
    if($block->getData('itemTextStyle') != ''):
        $selectedItemTextStyle = str_replace(',' , '', $block->getData('itemTextStyle'));
    endif;


    //If value exists for headlineBannerStyle pull in the value and replace the comma for a space
    if($block->getData('headlineBannerStyle') != ''):
      $selectedHeadlineBannerStyle = str_replace(',' , '', $block->getData('headlineBannerStyle'));
    endif;


    $html = '';

    $i = 0;
    foreach($items as $item):
        if($this->getData($item) != ''):
            $html .= '<li class="list-icon-detail">' . '<span class="list-icon-detail-test" 
style="color:' . $block->getData('itemTextColor') . '; ' . trim($selectedItemTextSize) . trim($selectedItemTextStyle) .
              '">' . $block->getData($item) . '</span>';

            if($this->getData($item_icons[$i]) != ''):
                $html .= '<img src="' . $block->getData($item_icons[$i]) . '" />';
            endif;

            $html .= '</li>';
        endif;

        $i++;
    endforeach;
?>
<section class="product-info-container align-top widget-margin">
    <div class="product-info grid col-2">
        <h2 class="span_6_of_12 list-icon-header" style="color:<?php echo $block->escapeHtmlAttr($block->getData('headlinecolor'));?>;
        <?php echo /* @noEscape */ $block->escapeHtml($selectedHeadlineBannerStyle);?>"><?php
          echo /* @noEscape */ $block->escapeHtml($block->getData('headline')); ?></h2>
        <ul class="span_6_of_12 list-icon">
            <?php echo /* @noEscape */ $block->escapeHtml($html); ?>
        </ul>
    </div>
</section>

