<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php

/*
 * Show combined price instead of minimal price for grouped products.
 */
$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
$regularPrice = 0;
$specialPrice = 0;           
foreach ($_associatedProducts as $child) {
  if ($child->getId() != $_product->getId()) {
        $regularPrice += $child->getPrice();
        $specialPrice += $child->getFinalPrice();
  }
}
?>
<div class="product attribute grouped-title-section">

    <!-- Grouped Product Name -->
    <h2 class="grouped-product-header"><?= /* @escapeNotVerified */ $_product->getData('name');?></h2>

    <!-- Grouped Short Description -->
  <?= /* @escapeNotVerified */ $_product->getData('short_description');?>
</div>
<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= $block->escapeHtml(__('Grouped product items')) ?></caption>
        <thead>
        <tr>
            <th class="col item grouphead" scope="col"><?= $block->escapeHtml(__('Product Name')) ?></th>
            <?php if ($_product->isSaleable()) : ?>
                <th class="col qty grouphead" scope="col"><?= 'Quantity'; ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts) : ?>
        <tbody>
            <?php foreach ($_associatedProducts as $_item) : ?>
            <tr>
                <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col item">
                    <strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($_product)) : ?>
                        <?php if ($block->getCanShowProductPrice($_item)) : ?>
                            <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                        <?php endif; ?>
                </td>
                <?php if ($_product->isSaleable()) : ?>
                <td data-th="<?= $block->escapeHtmlAttr(__('Quantity')) ?>" class="col qty product-qty-td">
                    <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty">
                        <input type="number"
                               id="super_group_<?= $block->escapeHtmlAttr($_item->getId()) ?>"
                               name="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               data-selector="super_group[<?= $block->escapeHtmlAttr($_item->getId()) ?>]"
                               value="<?= '1'; ?>"
                               title="<?= $block->escapeHtmlAttr(__('Quantity')) ?>"
                               class="input-text qty groupdrupalqty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"
                               data-mage-init='{ "Magento_GroupedProduct/js/quantity-changer": {"id": <?php echo $_item->getId(); ?>} }'/>
                    </div>
                <?php else : ?>
                    <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                        <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))) : ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
        <tr class="row-tier-price">
            <td colspan="2"><span class="totalgroupedprice"><?= $formattedPrice = $priceHelper->currency($specialPrice, true, false); ?></span></td>
        </tr>
        </tbody>
        <?php else : ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()) : ?>4<?php else : ?>3<?php endif; ?>">
                    <?= $block->escapeHtml(__('No options of this product are available.')) ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
<!-- Call JS file using RequireJS -->
<script>
    require(["SMG_GroupedAssociatedProducts/js/product-switcher"]);
</script>
