<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<!-- Define Variables -->
<?php
$i = 1;
$x = 1;
?>


<!-- Call JS file using RequireJS -->
<script>
    require(["SMG_GroupedAssociatedProducts/js/product-switcher"]);
</script>

<!-- Grouped Table -->
<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr class="grouped-table-titles">
            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>
        <?php if ($_hasAssociatedProducts): ?>
            <?php foreach ($_associatedProducts as $_item): ?>
                <tbody>
                <tr class="grouped-row" id="product_summary_id__<?php echo $i;?>">
                    <?php $i++;?>
                    <td class="col item product-detail-td">
                        <!-- Simple Product Short Description -->
                        <?= /* @escapeNotVerified */ $_item->getData('short_description');?>


                        <!-- Insert Product Price -->
                        <?php if ($block->getCanShowProductPrice($_product)): ?>
                            <?php if ($block->getCanShowProductPrice($_item)): ?>
                                <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if ($_product->isSaleable()): ?>
                        <td class="col qty product-qty-td">
                            <?php if ($_item->isSaleable()) : ?>
                                <div class="control qty">
                                    <input type="number"
                                           id="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                           name="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                           data-selector="super_group[<?= /* @escapeNotVerified */ $_item->getId() ?>]"
                                           value="<?= $_item->getQty() ?>"
                                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                           class="input-text qty"
                                           data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                           data-errors-message-box="#validation-message-box"/>
                                </div>
                            <?php else: ?>
                                <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
                                    <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                </div>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))): ?>
                    <tr class="row-tier-price">
                        <td colspan="2">
                            <?= $block->getProductPriceHtml(
                                $_item,
                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                            ) ?>
                        </td>
                    </tr>
                <?php endif; ?>
                </tbody>
            <?php endforeach; ?>
        <?php else: ?>
            <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
                </td>
            </tr>
            </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>