<?php
$orderId = $this->getRequest()->getParam('order_id');
?>
<div class="fieldset-wrapper">
	<div class="fieldset-wrapper-title"><span class="title">Scott's Subscriptions</span></div>
	<?php
	$subscriptions = $block->getCustomerSubscriptions();

	$subscriptionProductsArray = $block->getSubscriptionProducts();

	if ($subscriptions['success'] == true && (!empty($subscriptions['subscriptionInfo']['activeSubscriptions']))) {
		$adminPath = $this->escapeHtml($block->getAdminURLPath());
	?>
		<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
			<table class="data-grid">
				<thead>
					<tr>
						<th class="data-grid-th no-link">Subscription ID</th>
						<th class="data-grid-th no-link">Quiz ID</th>
						<th class="data-grid-th no-link">Subscription Plan</th>
						<th class="data-grid-th no-link">Status</th>
						<th class="data-grid-th no-link">Magento Status</th>
						<th class="data-grid-th no-link">SAP Order Status</th>
						<th class="data-grid-th no-link">Subscribed On</th>
						<th class="data-grid-th no-link">Starts On</th>
						<th class="data-grid-th no-link">Amount</th>
						<th class="data-grid-th no-link">Product Name</th>
						<th class="data-grid-th no-link">Sku</th>
						<th class="data-grid-th no-link">Qty</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($subscriptions['subscriptionInfo']['activeSubscriptions'] as $subscription) { ?>
						<tr onclick='location.href = this.getElementsByTagName("a").item(0).getAttribute("href");'>
                            <td><?php echo $this->escapeHtml($subscription['parentSubscription']['subscription_id']); ?></td>
							<td><?php echo (isset($subscription['parentSubscription']['quiz_id'])) ? $this->escapeHtml($subscription['parentSubscription']['quiz_id']) : 'Quiz ID does not exist for this subscription.'; ?></td>
							<td><?php echo $this->escapeHtml($subscription['recurlySubscription']->plan->name); ?></td>
							<td><?php echo $this->escapeHtml($subscription['parentSubscription']['subscription_status']); ?></td>
							<td></td>
							<td></td>
							<td><?php echo $subscription['recurlySubscription']->activated_at->format('d F, Y'); ?></td>
							<td><?php echo $subscription['recurlySubscription']->current_term_started_at->format('d F, Y'); ?></td>
							<td>$<?php echo $block->convertAmountToDollars($subscription['recurlySubscription']->unit_amount_in_cents); ?></td>
							<td></td>
							<td></td>
							<td></td>
						</tr>
                        <?php foreach ($subscription['subscriptionOrders'] as $subscriptionOrder) { ?>
                            <tr onclick='location.href = this.getElementsByTagName("a").item(0).getAttribute("href");'>
                                <td>
                                    <a href="/<?php echo $this->escapeHtml($adminPath); ?>/sales/order/view/order_id/<?php echo $this->escapeHtml($subscriptionOrder['salesOrder']['entity_id']); ?>"><?php echo $this->escapeHtml($subscriptionOrder['subscriptionOrder']['subscription_id']); ?></a>
                                </td>
                                <td><?php echo (isset($subscription['parentSubscription']['quiz_id'])) ? $this->escapeHtml($subscription['parentSubscription']['quiz_id']) : 'Quiz ID does not exist for this subscription.'; ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['recurlySubscription']->plan->name); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['subscriptionOrder']['subscription_order_status']); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['salesOrder']['status']); ?></td>
                                <td><?php echo $this->escapeHtml($block->getSapOrderStatus($subscriptionOrder['subscriptionOrder']['subscription_id'])); ?></td>
                                <td><?php echo $subscriptionOrder['recurlySubscription']->activated_at->format('d F, Y'); ?></td>
                                <td><?php echo $subscriptionOrder['recurlySubscription']->current_term_started_at->format('d F, Y'); ?></td>
                                <td>$<?php echo $block->convertAmountToDollars($subscriptionOrder['recurlySubscription']->unit_amount_in_cents); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['product']['name']); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['product']['sku']); ?></td>
                                <td><?php echo $this->escapeHtml(round($subscriptionOrder['product']['qty_ordered'])); ?></td>
                            </tr>
                        <?php } ?>
					<?php } ?>
                    <?php foreach ($subscriptions['subscriptionInfo']['renewedSubscriptions'] as $subscription) { ?>
                        <tr onclick='location.href = this.getElementsByTagName("a").item(0).getAttribute("href");'>
                            <td><?php echo $this->escapeHtml($subscription['parentSubscription']['subscription_id']); ?></td>
                            <td><?php echo (isset($subscription['parentSubscription']['quiz_id'])) ? $this->escapeHtml($subscription['parentSubscription']['quiz_id']) : 'Quiz ID does not exist for this subscription.'; ?></td>
                            <td><?php echo $this->escapeHtml($subscription['recurlySubscription']->plan->name); ?></td>
                            <td><?php echo $this->escapeHtml($subscription['parentSubscription']['subscription_status']); ?></td>
                            <td></td>
                            <td></td>
                            <td><?php echo $subscription['recurlySubscription']->activated_at->format('d F, Y'); ?></td>
                            <td><?php echo $subscription['recurlySubscription']->current_term_started_at->format('d F, Y'); ?></td>
                            <td>$<?php echo $block->convertAmountToDollars($subscription['recurlySubscription']->unit_amount_in_cents); ?></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <?php foreach ($subscription['subscriptionOrders'] as $subscriptionOrder) { ?>
                            <tr onclick='location.href = this.getElementsByTagName("a").item(0).getAttribute("href");'>
                                <td>
                                    <a href="/<?php echo $this->escapeHtml($adminPath); ?>/sales/order/view/order_id/<?php echo $this->escapeHtml($subscriptionOrder['salesOrder']['entity_id']); ?>"><?php echo $this->escapeHtml($subscriptionOrder['subscriptionOrder']['subscription_id']); ?></a>
                                </td>
                                <td><?php echo (isset($subscription['parentSubscription']['quiz_id'])) ? $this->escapeHtml($subscription['parentSubscription']['quiz_id']) : 'Quiz ID does not exist for this subscription.'; ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['recurlySubscription']->plan->name); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['subscriptionOrder']['subscription_order_status']); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['salesOrder']['status']); ?></td>
                                <td><?php echo $this->escapeHtml($block->getSapOrderStatus($subscriptionOrder['subscriptionOrder']['subscription_id'])); ?></td>
                                <td><?php echo $subscriptionOrder['recurlySubscription']->activated_at->format('d F, Y'); ?></td>
                                <td><?php echo $subscriptionOrder['recurlySubscription']->current_term_started_at->format('d F, Y'); ?></td>
                                <td>$<?php echo $block->convertAmountToDollars($subscriptionOrder['recurlySubscription']->unit_amount_in_cents); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['product']['name']); ?></td>
                                <td><?php echo $this->escapeHtml($subscriptionOrder['product']['sku']); ?></td>
                                <td><?php echo $this->escapeHtml(round($subscriptionOrder['product']['qty_ordered'])); ?></td>
                            </tr>
                        <?php } ?>
                    <?php } ?>
				</tbody>
			</table>
			<div>
				<p>Clicking "Cancel Subscription" will cancel all of it's active and future subscriptions.</p>
				<form action="<?php echo $block->getCancelUrl(); ?>" method="POST">
					<input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>" />
					<input type="hidden" name="recurly_account_code" value="<?php echo $subscriptions['subscriptionInfo']['customer']['gigya_uid']; ?>" />
					<button type="submit">Cancel Subscription</button>
				</form>
			</div>
		</div>
	<?php } else { ?>
		<?php if ($subscriptions['success'] == false) { ?>
			<p><?php echo $subscriptions['error_message']; ?></p>
		<?php } else { ?>
			<p>This customer does not have any active or future subscriptions.</p>
		<?php } ?>
	<?php } ?>
</div>
