<div
    class="sp-plan sp-flex sp-relative"
    data-bind="scope: 'yourPlan'"
>
    <div class="sp-plan sp-flex sp-flex-column sp-h-full sp-w-full">
        <!-- ko template: "SMG_SubscriptionPlan/index.html" --><!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "yourPlan": {
                        "component": "SMG_SubscriptionPlan/js/your-plan",
                        "customer_first_name": "<?= $block->escapeHtml($block->getFirstName()) ?>",
                        "subscription": <?= $block->getSubscription() ? $block->getSubscription()->toJson() : 'null'; ?>
                    }
                }
            }
        }
    }
</script>
