<div id="ajax_event">
<?php

$helper = $block->getHelper();
$smghelper = $this->helper('SMG\Launch\Helper\Data');

$updateditems = $smghelper->getCheckoutSession()->getUpdateqty();

if ($updateditems) :
    foreach($updateditems as $pro){ ?>

        <script>

            window.dtmData.events.push({
                name: 'cartUpdate',
                product: {
					id: '<?php echo $block->escapeHtml($pro["id"]);?>',
					name: '<?php $p_name = $pro["name"]; echo $block->escapeHtml(str_replace("™","",$p_name)); ?>',
					currency: '<?php echo $block->escapeHtml($block->getCurrencyCode());?>',
					unitPrice: <?php echo $block->escapeHtml($pro["unitPrice"]);?>,
					sku: '<?php echo $block->escapeHtml($pro["sku"]);?>',
					quantity: <?php echo $block->escapeHtml($pro["quantity"]);?>,
					previousQuantity: <?php echo $block->escapeHtml($pro["previousQuantity"]);?>
                }

            });

        </script>

    <?php }
    $smghelper->getCheckoutSession()->unsUpdateqty();
endif; ?>
</div>