<?php
$helper = $block->getHelper();
$smghelper = $this->helper('SMG\Launch\Helper\Data');
$item = $smghelper->getCheckoutSession()->getDtmAddToCart();
?>
<?php if ($item) : ?>
<script>
window.dtmData.events.push({

	name: 'cartAdd',

	product: {
		<?php foreach($smghelper->getCheckoutSession()->getDtmAddToCart() as $pro){ ?>
		id: '<?php echo $block->escapeHTML($pro['id']);?>',
		name: '<?php $p_name = $pro['name']; echo $block->escapeHTML(str_replace("™","",$p_name)); ?>',
		category: ['<?php echo $block->escapeHTML($pro['category']);?>'],
		currency: '<?php echo $block->escapeHTML($block->getCurrencyCode());?>',
		unitPrice: <?php echo $block->escapeHTML($pro['unitPrice']);?>,
		sku: '<?php echo $block->escapeHTML($pro['sku']);?>',
		quantity: <?php echo $block->escapeHTML($pro['quantity']);?>

		<?php } ?>

	}

});
</script>
<?php $smghelper->getCheckoutSession()->unsDtmAddToCart();?>
<?php endif; ?>

<?php /*Newsletter event*/ ?>
<?php $newsletter = $smghelper->getCatalogSession()->getDtmNewsletter(); ?>
<?php if($newsletter) : ?>
	<script>
	window.dtmData.events.push({
		name: 'newsletterSuccess',
		email: '<?php echo $block->escapeHTML($newsletter);?>'
	});
	</script>

<?php $smghelper->getCatalogSession()->unsDtmNewsletter();?>
<?php endif; ?>

<?php /*update qty event*/ ?>

<?php $updateditems = $smghelper->getCheckoutSession()->getUpdateqty(); ?>
<?php if ($updateditems) : ?>
<?php foreach($updateditems as $pro){ ?>
	<script>
	window.dtmData.events.push({
		name: 'cartUpdate',
		product: {
			id: '<?php echo $block->escapeHTML($pro['id']);?>',
			name: '<?php $p_name = $pro['name']; echo $block->escapeHTML(str_replace("™","",$p_name)); ?>',
			category: [<?php echo $block->escapeHTML($pro['category']);?>],
			currency: '<?php echo $block->escapeHTML($block->getCurrencyCode());?>',
			unitPrice: <?php echo $block->escapeHTML($pro['unitPrice']);?>,
			sku: '<?php echo $block->escapeHTML($pro['sku']);?>',
			quantity: <?php echo $block->escapeHTML($pro['quantity']);?>,
			previousQuantity: <?php echo $block->escapeHTML($pro['previousQuantity']);?>
		}
	});
	</script>
<?php } ?>
<?php $smghelper->getCheckoutSession()->unsUpdateqty(); ?>
<?php endif; ?>


<?php /*delete item event*/ ?>
<?php $deleteitem = $smghelper->getCheckoutSession()->getDeleteitem(); ?>
<?php if ($deleteitem) : ?>
	<script>
	window.dtmData.events.push({
		name: 'cartRemove',
		product: {
			id: '<?php echo $block->escapeHTML($deleteitem['id']);?>',
			name: '<?php $p_name = $deleteitem['name']; echo $block->escapeHTML(str_replace("™","",$p_name)); ?>',
			category: [<?php echo $block->escapeHTML($deleteitem['category']);?>],
			currency: '<?php echo $block->escapeHTML($block->getCurrencyCode());?>',
			unitPrice: <?php echo $block->escapeHTML($deleteitem['unitPrice']);?>,
			sku: '<?php echo $block->escapeHTML($deleteitem['sku']);?>',
			quantity: <?php echo $block->escapeHTML($deleteitem['quantity']);?>,
		}
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*coupen event*/ ?>
<?php $coupen = $smghelper->getCheckoutSession()->getCoupen(); ?>
<?php if ($coupen) : ?>
	<script>
	window.dtmData.events.push({
		name: 'promoApplied',
		promoCode:'<?php echo $block->escapeHTML($coupen); ?>',
		success: '<?php if($smghelper->getCheckoutCart()->getQuote()->getCouponCode() == $coupen){ echo "true"; }else{ echo "false"; } ?>'
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*contact error*/ ?>
<?php $errorcontact = $smghelper->getCheckoutSession()->getContactError(); ?>
<?php if($errorcontact):?>
	<script>
	window.dtmData.events.push({
		name: 'errorMessage',
		errorMessage:'<?php echo $block->escapeHTML($errorcontact); ?>'
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsContactError(); ?>
<?php endif;  ?>
