<?php
$helper = $block->getHelper();
$smghelper = $this->helper('SMG\Launch\Helper\Data');
$item = $smghelper->getCheckoutSession()->getDtmAddToCart();
?>
<?php if ($item) : ?>
    <script>

        window.dtmData.events.push({
            name: 'cartAdd',
            product: {
                <?php foreach($smghelper->getCheckoutSession()->getDtmAddToCart() as $pro){ ?>
                id: '<?php echo $block->escapeHtml($pro["id"]);?>',
                name: '<?php $p_name = $pro["name"]; echo $block->escapeHtml(str_replace("™","",$p_name)); ?>',
                category: ['<?php echo $block->escapeHtml($pro["category"]);?>'],
                        currency: '<?php echo $block->escapeHtml($block->getCurrencyCode());?>',
                unitPrice: <?php echo $block->escapeHtml($pro["unitPrice"]);?>,
                sku: '<?php echo $block->escapeHtml($pro["sku"]);?>',
                <?php if (!empty($pro['drupalproductid'])): ?>
                drupalproductid:  '<?php echo $block->escapeHtml($pro['drupalproductid']) ?>',
                <?php endif; ?>
                quantity: <?php echo $block->escapeHtml($pro["quantity"]);?>
                <?php } ?>
            }
        });
    </script>
    <?php $smghelper->getCheckoutSession()->unsDtmAddToCart();?>
<?php endif; ?>

<?php /*Newsletter event*/ ?>
<?php $newsletter = $smghelper->getCatalogSession()->getDtmNewsletter(); ?>
<?php if($newsletter) : ?>
    <script>
        window.dtmData.events.push({
            name: 'newsletterSuccess',
            email: '<?php echo $block->escapeHtml($newsletter);?>'
        });
    </script>

    <?php $smghelper->getCatalogSession()->unsDtmNewsletter();?>
<?php endif; ?>

<?php /*update qty event*/ ?>



<?php /*delete item event*/ ?>
<?php $deleteitem = $smghelper->getCheckoutSession()->getDeleteitem(); ?>
<?php if ($deleteitem) : ?>
    <script>
        window.dtmData.events.push({
            name: 'cartRemove',
            product: {
			id: '<?php echo $block->escapeHtml($deleteitem["id"]);?>',
			name: '<?php $p_name = $deleteitem["name"]; echo $block->escapeHtml(str_replace("™","",$p_name)); ?>',
			category: '<?php echo $block->escapeHtml($deleteitem["category"]);?>',
                currency: '<?php echo $block->escapeHtml($block->getCurrencyCode());?>',
			unitPrice: <?php echo $block->escapeHtml($deleteitem["unitPrice"]);?>,
			sku: '<?php echo $block->escapeHtml($deleteitem["sku"]);?>',
            <?php if (!empty($deleteitem['drupalproductid'])): ?>
            drupalproductid:  '<?php echo $block->escapeHtml($deleteitem['drupalproductid']) ?>',
            <?php endif; ?>
			quantity: <?php echo $block->escapeHtml($deleteitem["quantity"]);?>,
            }
        });
    </script>
    <?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*coupen event*/ ?>
<?php $coupen = $smghelper->getCheckoutSession()->getCoupen(); ?>
<?php if ($coupen) : ?>
    <script>
        window.dtmData.events.push({
            name: 'promoApplied',
            promoCode:'<?php echo $block->escapeHtml($coupen); ?>',
            success: '<?php if($smghelper->getCheckoutCart()->getQuote()->getCouponCode() == $coupen){ echo "true"; }else{ echo "false"; } ?>'
        });
    </script>
    <?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*contact error*/ ?>
<?php $errorcontact = $smghelper->getCheckoutSession()->getContactError(); ?>
<?php if($errorcontact):?>
    <script>
        window.dtmData.events.push({
            name: 'errorMessage',
            errorMessage:'<?php echo $block->escapeHtml($errorcontact); ?>'
        });
    </script>
    <?php $smghelper->getCheckoutSession()->unsContactError(); ?>
<?php endif;  ?>

<?php /* Product Page Tab */ ?>
<script type="text/x-magento-init">
{
	"*": {
			"SMG_Launch/launch": {}
		}
}
</script>

