<?php
$helper = $block->getHelper();
$smghelper = $this->helper('SMG\Launch\Helper\Data');
$item = $smghelper->getCheckoutSession()->getDtmAddToCart();  
?> 
<?php if ($item) : ?>
<script>
window.dtmData.events.push({

	name: 'cartAdd',

	product: {
		<?php foreach($smghelper->getCheckoutSession()->getDtmAddToCart() as $pro){ ?>
		id: '<?php echo $pro['id'];?>',
		name: '<?php $p_name = $pro['name']; echo str_replace("™","",$p_name); ?>',
		category: [<?php echo $pro['category'];?>],
		currency: '<?php echo $block->getCurrencyCode();?>',
		unitPrice: <?php echo $pro['unitPrice'];?>,
		sku: '<?php echo $pro['sku'];?>',
		quantity: <?php echo $pro['quantity'];?>
		
		<?php } ?>

	}

});
</script>
<?php $smghelper->getCheckoutSession()->unsDtmAddToCart();?>
<?php endif; ?>

<?php /*Newsletter event*/ ?>
<?php $newsletter = $smghelper->getCatalogSession()->getDtmNewsletter(); ?>
<?php if($newsletter) : ?>
	<script>
	window.dtmData.events.push({
		name: 'newsletterSuccess',
		email: '<?php echo $newsletter;?>'
	});
	</script>
	
<?php $smghelper->getCatalogSession()->unsDtmNewsletter();?>	
<?php endif; ?>

<?php /*update qty event*/ ?>

<?php $updateditems = $smghelper->getCheckoutSession()->getUpdateqty(); ?>
<?php if ($updateditems) : ?>
<?php foreach($updateditems as $pro){ ?>
	<script>
	window.dtmData.events.push({
		name: 'cartUpdate',
		product: {
			id: '<?php echo $pro['id'];?>',
			name: '<?php $p_name = $pro['name']; echo str_replace("™","",$p_name); ?>',
			category: [<?php echo $pro['category'];?>], 
			currency: '<?php echo $block->getCurrencyCode();?>',
			unitPrice: <?php echo $pro['unitPrice'];?>,
			sku: '<?php echo $pro['sku'];?>',
			quantity: <?php echo $pro['quantity'];?>,
			previousQuantity: <?php echo $pro['previousQuantity'];?>
		}
	});
	</script>
<?php } ?>
<?php $smghelper->getCheckoutSession()->unsUpdateqty(); ?>
<?php endif; ?>


<?php /*delete item event*/ ?>
<?php $deleteitem = $smghelper->getCheckoutSession()->getDeleteitem(); ?>
<?php if ($deleteitem) : ?>
	<script>
	window.dtmData.events.push({
		name: 'cartRemove',
		product: {
			id: '<?php echo $deleteitem['id'];?>',
			name: '<?php $p_name = $deleteitem['name']; echo str_replace("™","",$p_name); ?>',
			category: [<?php echo $deleteitem['category'];?>], 
			currency: '<?php echo $block->getCurrencyCode();?>',
			unitPrice: <?php echo $deleteitem['unitPrice'];?>,
			sku: '<?php echo $deleteitem['sku'];?>',
			quantity: <?php echo $deleteitem['quantity'];?>,
		}
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*coupen event*/ ?>
<?php $coupen = $smghelper->getCheckoutSession()->getCoupen(); ?>
<?php if ($coupen) : ?>
	<script>
	window.dtmData.events.push({
		name: 'promoApplied',
		promoCode:'<?php echo $coupen; ?>',
		success: '<?php if($smghelper->getCheckoutCart()->getQuote()->getCouponCode() == $coupen){ echo "true"; }else{ echo "false"; } ?>'
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsDeleteitem(); ?>
<?php endif; ?>

<?php /*contact error*/ ?>
<?php $errorcontact = $smghelper->getCheckoutSession()->getContactError(); ?>
<?php if($errorcontact):?>
	<script>
	window.dtmData.events.push({
		name: 'errorMessage',
		errorMessage:'<?php echo $errorcontact; ?>'
	});
	</script>
<?php $smghelper->getCheckoutSession()->unsContactError(); ?>
<?php endif;  ?>

<?php /* Product Page Tab */ ?>

<script>
require([
    'jquery',
], function ($) {
    $(document).ready(function(){
		 $('.product.info.detailed a').on("click",function(){
			var tabtext = $(this).text();
			var trimStr = $.trim(tabtext);
			$('#tabclick_event').remove();
			$(".product-info-main").append("<div id='tabclick_event'><script>dtmData.events.push({name: 'tabClick',tabName:'"+trimStr+"'});<\/script><\/div>");
		});
	});
});
</script>