<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore()->getCode();
$helper = $block->getHelper();
if (!$helper->isSmgEnabled($store)) {
	return;
}
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');

$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$cart_id = $cart->getQuote()->getId();
$script = $helper->getScript($store);
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$currentPage = $request->getFullActionName();

$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$subTotal = $cart->getQuote()->getSubtotal();
$items = $cart->getQuote()->getAllItems();

$name = $block->getLayout()->getBlock('page.main.title')->getPageTitle();

$type = '';
if($currentPage == 'cms_index_index'){
	$type = 'home';	
}else if($currentPage == 'catalog_category_view'){
	$type = 'collection';	
}else if($currentPage == 'catalog_product_view'){
	$type = 'product';	
}else if($currentPage == 'checkout_cart_index'){
	$type = 'cart';	
}else if($currentPage == 'checkout_index_index '){
	$type = 'checkout';	
}else if($currentPage == 'customer_account_index'){
	$type = 'customer';	
}else if($currentPage == 'checkout_onepage_success'){
	$type = 'order_success';	
}else if($currentPage == 'catalogsearch_result_index'){
	$type = 'search';	
}      
 

?>
<!-- Adobe Launch Code -->
<script src="<?php echo $script?>"></script>
<script>
   window.dtmData = {
	  events: [],
	  page: {
		cms: 'M2',
		type: '<?php echo $type;?>',
		name: '<?php echo str_replace("™","",$name); ?>',
		<?php if($currentPage == 'catalog_category_view'){ ?>
		channel: 'catalog',
		content_type: 'productcatalog',
		<?php } ?>
		<?php if($currentPage == 'catalog_product_view'){ ?>
		type: 'product',
		<?php } ?>
		<?php if($currentPage == 'catalogsearch_result_index'){ ?>
		type: 'search',
		<?php } ?>
		<?php if($currentPage == 'checkout_onepage_success'){ ?>
		type: 'confirmation',
		<?php } ?>
		site: '<?php echo $store;?>' 
		preffered_local: 'english',
		rendered_local: 'english' 
	  },
	  <?php if($customerSession->isLoggedIn()) {?>
	   user: {
		userId: '<?php echo $customerSession->getCustomer()->getId();?>', 
		email: '<?php echo $customerSession->getCustomer()->getEmail();?>',
		isLoggedIn: 1,
		zip: '',	
		cartId: '<?php echo $cart_id;?>'
	  },
	  <?php }else{?>
	  user: {
		userId: '', 
		email: '',
		isLoggedIn: ,
		zip: '',
		cartId: '<?php echo $cart_id;?>' 
	  },
	  <?php } ?>
	  <?php if($currentPage != 'checkout_onepage_success'){ ?>
	  cart: {
		currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
		subtotal: <?php echo $subTotal;?>, 
		promoCode: '<?php echo $cart->getQuote()->getCouponCode();?>', 
		lineItems: [ 
		<?php foreach($items as $item) {
			$product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
			$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
			$productImageUrl = '';
			if($product->getImage()){
				$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
			}
			$productUrl  = $product->getProductUrl();
			
			$categoryIds = $product->getCategoryIds();
			$categories = $categoryCollection->create()
                                 ->addAttributeToSelect('*')
                                 ->addAttributeToFilter('entity_id', $categoryIds);
			$cats = [];
			foreach ($categories as $category) {
				$cats[] = $category->getName();
			}					 
		?>
		  {
			  id: '<?php echo $item->getProductId();?>',
			  name: '<?php $p_name = $item->getName(); echo str_replace("™","",$p_name); ?>', 
			  category: [
			  <?php foreach ($categories as $category) {?>
					'<?php echo $category->getName();?>',
			  <?php } ?>
			  ],
			  currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
			  unitPrice: <?php echo $item->getPrice();?>,
			  sku: '<?php echo $item->getSku();?>', 
			  imageUrl: '<?php echo $productImageUrl;?>',  
			  quantity: <?php echo $item->getQty();?>,
			  url: '<?php echo $productUrl;?>'
		  }<?php if (!($item === end($items))) { echo ','; } ?>
		<?php } ?>
		]
	  },
	  <?php } ?>
	  <?php if($currentPage == 'catalog_category_view'){ 
			$cat = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
			$category = $objectManager->create('Magento\Catalog\Model\Category')->load($cat->getId());
			$product_count = $category->getProductCount(); ?>
		listing: {
			resultCount:'<?php echo $product_count;?>',
			layout: '<?php if(isset($_REQUEST['product_list_mode'])){ echo $_REQUEST['product_list_mode']; }else{ echo "grid"; } ?>', 
			pageName: '<?php echo $name;?>',
		}
		<?php } ?>
		<?php if($currentPage == 'catalog_product_view'){ 
		$pro = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
		$product = $objectManager->get('Magento\Catalog\Model\Product')->load($pro->getId());
		?>
		product: {
			id: '<?php echo $product->getId()?>',
			product_category_id: '<?php echo implode(',',$product->getCategoryIds());?>',
			purchase_online: <?php echo $product->getStatus();?> ,
			name: '<?php $p_name = $product->getName(); echo str_replace("™","",$p_name); ?> ',
			currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
			unitPrice: '<?php echo $product->getPrice(); ?>',
			sku: '<?php echo $product->getSku(); ?>', 
			inStock: <?php echo $product->getIsSalable(); ?>
		
		}
		<?php } ?>
		<?php if($currentPage == 'catalogsearch_result_index'){ ?>
		listing: {
			query: '<?php echo $_REQUEST['q'];?>',
			sortBy: '<?php if(isset($_REQUEST['product_list_order'])){ echo $_REQUEST['product_list_order']; }else{ echo "default"; } ?>',
			layout: '<?php if(isset($_REQUEST['product_list_mode'])){ echo $_REQUEST['product_list_mode']; }else{ echo "grid"; } ?>',
			pageName: "<?php echo $block->getLayout()->getBlock('page.main.title')->getPageTitle(); ?>",
		}
		<?php } ?>
		<?php if($currentPage == 'checkout_onepage_success'){ 
		
				$checkoutSession = $objectManager->get('Magento\Checkout\Model\Session');
				$order = $checkoutSession->getLastRealOrder();
				$orderId = $order->getId();
				$items = $order->getAllVisibleItems(); 
			?>
		transaction: {
			orderId: '<?php echo $orderId;?>', 
			currency: '<?php echo $order->getOrderCurrencyCode(); ?>',
			subtotal: <?php echo (float)$order->getSubtotal(); ?>,
			shippingCost: <?php echo (float)$order->getShippingAmount(); ?>,
			tax: <?php echo (float)$order->getTaxAmount(); ?>,
			total: <?php echo (float)$order->getGrandTotal(); ?>,
			paymentMethod: '<?php echo $order->getPaymentMethod(); ?>', 
			shippingMethod: '<?php echo $order->getShippingMethod(); ?>',
			lineItems: [ 
			<?php foreach($items as $item) {
				$product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
				$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
				$productImageUrl = '';
				if($product->getImage()){
					$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
				}
				$productUrl  = $product->getProductUrl();
				
				$categoryIds = $product->getCategoryIds();
				$categories = $categoryCollection->create()
									 ->addAttributeToSelect('*')
									 ->addAttributeToFilter('entity_id', $categoryIds);
				$cats = [];
				foreach ($categories as $category) {
					$cats[] = $category->getName();
				}					 
			?>
			  {
				  id: '<?php echo $item->getProductId();?>',
				  name: '<?php $p_name = $item->getName(); echo str_replace("™","",$p_name); ?>', 
				  category: [
				  <?php foreach ($categories as $category) {?>
						'<?php echo $category->getName();?>',
				  <?php } ?>
				  ],
				  currency: '<?php echo $order->getOrderCurrencyCode();?>',
				  unitPrice: <?php echo $item->getPrice();?>,
				  sku: '<?php echo $item->getSku();?>', 
				  imageUrl: '<?php echo $productImageUrl;?>',  
				  quantity: <?php echo $item->getQty();?>,
				  url: '<?php echo $productUrl;?>'
			  },
			<?php } ?>
			]
		}
		<?php } ?>
		
	}
	
	<?php if($currentPage == 'catalog_category_view'){ ?>
	<?php if(isset($_REQUEST)){
			$filters = array();
			foreach($_REQUEST as $key=>$data){
				if($key == 'product_list_mode' || $key == 'q' || $key == 'product_list_order'){
					continue;
				} 
				$filters['key'][] = $key;
				$filters['val'][] = $data;
			} ?>
			<?php if(count($filters)>0 ){ ?>
				window.dtmData.events.push({
					name: 'filterApplied',
					filterType: '<?php echo implode(',',$filters['key']);?>',
					filterValue: '<?php echo implode(',',$filters['val']);?>'
				});
			 <?php } ?>	
		<?php }?>
	<?php } ?>	
</script>
<!-- End Adobe Launch Code -->
