<style>
    .sp-how-it-works__heading-image {
        display: block;
        margin: 0 auto;
        max-width: 320px;
    }

    .sp-how-it-works__heading-image--bottom {
        max-width: 212px !important;
    }

    .sp-how-it-works__title {
        font-size: 50px;
    }

    @media (min-width: 768px) {
        .sp-how-it-works__heading-image {
            max-width: unset;
        }

        .sp-how-it-works__heading-image--bottom {
            max-width: unset !important;
        }

        .sp-how-it-works__title {
            font-size: 100px;
        }
    }

    .sp-vertical-divider {
        border-color: #1D5632;
        border-width: 2px;
        width: 6rem;
        transform: rotate(90deg);
        margin: 6rem auto;
    }

    .sp-quiz-preview {
        background-color: #EDF4E1;
        padding: 2rem;
    }

    @media (min-width: 1024px) {
        .sp-quiz-preview {
            background-color: transparent;
        }

        .sp-quiz-preview__question {
            margin-right: 6rem;
        }

        .sp-quiz-preview__description {
            margin-left: -12rem;
            padding-left: 12rem;
        }
    }
</style>

<div class="sp-how-it-works-page sp-py-8">
    <div class="sp-how-it-works__heading sp-container sp-flex sp-flex-column sp-items-center sp-mb-12">
        <div>
            <img class="sp-how-it-works__heading-image" src="https://test_magento_image_repo.storage.googleapis.com/howItWorks1.png" alt="How It Works">
        </div>
        <h1 class="sp-how-it-works__title sp-h0 sp-max-w-md sp-my-0 sp-px-4 sp-text-center sp-text-green-1">Here's How<br />It Works</h1>
        <div class="sp-mt-2">
            <img class="sp-how-it-works__heading-image sp-how-it-works__heading-image--bottom" src="https://test_magento_image_repo.storage.googleapis.com/howItWorks2.png" alt="How It Works">
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how-it-works__get-to-know">
        <div class="sp-container">
            <h2 class="sp-h2 sp-text-center sp-text-green-1">
                First, We Get to Know Your Lawn
            </h2>
            <div class="sp-quiz-preview sp-flex sp-flex-column lg:sp-flex-row lg:sp-grid">
                <div class="lg:sp-col-1/2">
                    <div
                        class="sp-quiz-preview__question sp-bg-green-1 sp-my-6 sp-relative sp-shadow-lg sp-z-1"
                    >
                        <ul class="sp-list-none sp-m-0 sp-p-8">
                            <li class="sp-bg-white sp-flex sp-items-center sp-mb-6 sp-p-4 sp-round sp-shadow-md">
                                <div class="sp-flex-none sp-pl-4 sp-pr-8">
                                    <input
                                        class="sp-radio"
                                        name="get-to-know"
                                        type="radio"
                                        value="1"
                                    />
                                </div>
                                <div class="sp-flex-auto">
                                    <h3 class="sp-h4 sp-mt-0 sp-mb-4 sp-uppercase">Lawn Condition 1</h3>
                                    <p class="sp-mb-0">Product details lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                                </div>
                            </li>
                            <li class="sp-bg-white sp-flex sp-items-center sp-mb-6 sp-p-4 sp-round sp-shadow-md">
                                <div class="sp-flex-none sp-pl-4 sp-pr-8">
                                    <input
                                        class="sp-radio"
                                        name="get-to-know"
                                        type="radio"
                                        value="1"
                                    />
                                </div>
                                <div class="sp-flex-auto">
                                    <h3 class="sp-h4 sp-mt-0 sp-mb-4 sp-uppercase">Lawn Condition 1</h3>
                                    <p class="sp-mb-0">Product details lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                                </div>
                            </li>
                            <li class="sp-bg-white sp-flex sp-items-center sp-mb-0 sp-p-4 sp-round sp-shadow-md">
                                <div class="sp-flex-none sp-pl-4 sp-pr-8">
                                    <input
                                        class="sp-radio"
                                        name="get-to-know"
                                        type="radio"
                                        value="1"
                                    />
                                </div>
                                <div class="sp-flex-auto">
                                    <h3 class="sp-h4 sp-mt-0 sp-mb-4 sp-uppercase">Lawn Condition 1</h3>
                                    <p class="sp-mb-0">Product details lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="lg:sp-col-1/2">
                    <div
                        class="sp-quiz-preview__description sp-bg-green-4 sp-flex sp-h-full sp-items-center sp-pt-8 lg:sp-p-20"
                    >
                        <ul class="sp-list-none sp-m-0 sp-p-0">
                            <li class="sp-mb-8">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    01. Overall Lawn Condition
                                </h4>
                                <p>Some of the considerations we take into account are your current grass color, thickness, weeds, and in some cases grass variety (if known).</p>
                            </li>
                            <li class="sp-mb-8">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    02. Geographic Region
                                </h4>
                                <p>Where you live has a significant impact on your lawn care needs. We make sure you’ve got the right product for your area.</p>
                            </li>
                            <li class="sp-mb-0">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    03. Lawn Size
                                </h4>
                                <p>In order to ensure we’re sending you the right amount of product, we need to find out what the approximate size of your lawn is. It’s simple with our lawn locator tool that helps you find and outline your lawn on a map.</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how__personalized-plan sp-mb-12">
        <div class="sp-container">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
                Next, We Create Your Personalized Lawn Care Plan
            </h2>

            <div class="md:sp-grid">
                <div class="sp-home__how-it-works-step md:sp-col-1/3 sp-mb-12 sp-text-center">
                    <img src="https://test_magento_image_repo.storage.googleapis.com/color.png" alt="Tell us about your lawn">
                    <h3 class="sp-h3 sp-mt-2">Seasons change and so do your deliveries</h3>
                    <p class="sp-text-sm">Our plan keeps up with the changing needs of your lawn and makes sure you get the right product to care for it throughout the year.</p>
                </div>
                <div class="sp-home__how-it-works-step md:sp-col-1/3 sp-mb-12 sp-text-center">
                    <img src="https://test_magento_image_repo.storage.googleapis.com/color copy.png" alt="Personalized plan">
                    <h3 class="sp-h3 sp-mt-2">Products that work better together</h3>
                    <p class="sp-text-sm">A simple way to treat your lawn with products that work together. Which means your lawn will keep growing green and strong.</p>
                </div>
                <div class="sp-home__how-it-works-step md:sp-col-1/3 sp-mb-12 sp-text-center">
                    <img src="https://test_magento_image_repo.storage.googleapis.com/color copy 2.png" alt="Products arrive">
                    <h3 class="sp-h3 sp-mt-2">Easy to use, backed by experience</h3>
                    <p class="sp-text-sm">We bring over 150 years of experience to every lawn care plan we create, helping you grow a yard that’ll be the talk of the block.</p>
                </div>
            </div>
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how__delivery sp-bg-green-4">
        <div class="sp-container sp-py-12">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
                Finally, We Deliver What You Need When You Need It
            </h2>

            <div class="md:sp-grid sp-items-center">
                <div class="md:sp-col-1/2">
                    <img
                        alt="Season Animation"
                        class="sp-block sp-mx-auto"
                        src="https://test_magento_image_repo.storage.googleapis.com/Animation.png"
                    />
                </div>

                <div class="md:sp-col-1/2 sp-text-center md:sp-text-left">
                    <h3>Just apply and enjoy</h3>
                    <p class="sp-mb-8">When your lawn needs something, you’ll receive a shipment with the product(s). Apply them to your lawn when they arrive and enjoy a beautiful yard. It’s seriously as simple as that.</p>
                    <a
                        href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>"
                        class="sp-button sp-button--primary sp-button--get-started sp-mb-12 sp-relative"
                    >
                        Get Started
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="sp-how__program">
        <div class="sp-container sp-py-12">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
                A Lawn Care Program that Works for You
            </h2>

            <div class="sp-flex sp-flex-column md:sp-flex-row md:sp-grid sp-items-center">
                <div class="md:sp-col-1/2 sp-mb-12 sp-order-1 md:sp-order-0">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">Flexible Payments</h3>
                        <p>You can either choose a seasonal subscription (pay-per shipment) or an annual subscription (one-time payment). Annual subscribers receive free shipping on every delivery.</p>
                    </div>
                </div>
                <div class="md:sp-col-1/2 md:sp-mb-12 sp-order-0 md:sp-order-1">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/subscription-options.png" alt="Subscription Options">
                    </div>
                </div>
                <div class="md:sp-col-1/2 md:sp-mb-12 sp-order-2">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/products.png" alt="Product Delivery">
                    </div>
                </div>
                <div class="md:sp-col-1/2 md:sp-flex sp-justify-end sp-mb-12 sp-order-3">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">Just-In-Time Delivery</h3>
                        <p>We send your product when it’s ready to be used. Which means all you need to do is wait for something to arrive and apply it when it does.</p>
                    </div>
                </div>
                <div class="md:sp-col-1/2 sp-mb-12 sp-order-5 md:sp-order-4">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">MyLawn Companion App</h3>
                        <p>If you really want to keep track of things, we’ve got an app that allows you to manage your plan at any time.</p>
                        <div class="sp-flex sp-justify-center md:sp-justify-start">
                            <a href="https://apps.apple.com/us/app/my-lawn-a-guide-to-lawn-care/id372269879?mt=8" target="_blank">
                                <img
                                    alt="App Store"
                                    class="sp-app-image sp-mr-4"
                                    src="https://test_magento_image_repo.storage.googleapis.com/badge--appstore.png"
                                    style="max-width: 8rem"
                                />
                            </a>
                            <a href="https://play.google.com/store/apps/details?id=com.scotts.lawnapp" target="_blank">
                                <img
                                    alt="Google Play"
                                    class="sp-app-image"
                                    src="https://test_magento_image_repo.storage.googleapis.com/badge--googleplay.png"
                                    style="max-width: 8rem"
                                />
                            </a>
                        </div>
                    </div>
                </div>
                <div class="md:sp-col-1/2 md:sp-mb-12 sp-order-4 md-sp-order-5">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/apps-bg-green.png" alt="Mobile Apps">
                    </div>
                </div>
            </div>

            <div class="sp-text-center">
                <a
                    href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>"
                    class="sp-button sp-button--primary sp-button--get-started sp-mb-12 sp-relative"
                >
                    Get Started
                </a>
            </div>
        </div>
    </div>
</div>
