<div class="sp-how-it-works-page sp-py-8">
    <div class="sp-how-it-works__heading sp-container sp-flex sp-flex-column sp-items-center sp-mb-12">
        <div>
            <img class="sp-how-it-works__heading-image" src="https://test_magento_image_repo.storage.googleapis.com/howItWorks1.png" alt="How It Works">
        </div>
        <h1 class="sp-how-it-works__title sp-h0 sp-max-w-md sp-my-0 sp-px-4 sp-text-center sp-text-green-1">Here's How<br />It Works</h1>
        <div class="sp-mt-2">
            <img class="sp-how-it-works__heading-image sp-how-it-works__heading-image--bottom" src="https://test_magento_image_repo.storage.googleapis.com/howItWorks2.png" alt="How It Works">
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how-it-works__get-to-know">
        <div class="sp-container">
            <h2 class="sp-h2 sp-text-center sp-text-green-1">
                First, We Get to Know Your Lawn
            </h2>
            <div class="sp-quiz-preview sp-flex sp-flex-column lg:sp-flex-row lg:sp--m-4">
                <div class="sp-how-it-works_lawn-condition">
                    <div
                        class="sp-my-6 sp-relative sp-z-1 sp-text-center"
                    >
                       <img src=" https://test_magento_image_repo.storage.googleapis.com/lawn_condition.png" alt="your lawn condition">
                    </div>
                </div>

                <div class="lg:sp-px-4 lg:sp-w-1/2">
                    <div
                        class="sp-quiz-preview__description sp-bg-green-4 sp-flex sp-h-full sp-items-center sp-pt-8 lg:sp-pr-16"
                    >
                        <ul class="sp-list-none sp-m-0 sp-p-0">
                            <li class="sp-mb-8">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    01. The Condition of Your Lawn
                                </h4>
                                <p>We consider the thickness and color of your grass, the amount of weeds in your yard, and more.</p>
                            </li>
                            <li class="sp-mb-8">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    02. Where You Live
                                </h4>
                                <p>Your location plays a big part in your lawn care needs. We'll pinpoint the right products for your area.</p>
                            </li>
                            <li class="sp-mb-0">
                                <h4 class="sp-h4 sp-mb-2 sp-mt-0">
                                    03. The Size of Your Lawn
                                </h4>
                                <p>Size matters, and we'll make sure to send you the right amount of product for your lawn.</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how__personalized-plan sp-mb-12">
        <div class="sp-container">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
                Next, We Create Your Personalized Lawn Care Plan
            </h2>

            <div class="md:sp-flex md:sp--mx-4">
                <div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-12 sp-px-4 sp-text-center">
                    <picture>
                        <source
                            srcset="https://test_magento_image_repo.storage.googleapis.com/color.png"
                            media="(min-width: 800px)"
                        >
                        <img alt="Tell us about your lawn" src="https://test_magento_image_repo.storage.googleapis.com/mobile.png" />
                    </picture>
                    <h3 class="sp-h3 sp-mt-2">Deliveries when you need them.</h3>
                    <p class="sp-text-sm">Your plan keeps up with the changing needs of your lawn, making sure you receive the right products at the right time throughout the year.</p>
                </div>
                <div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-12 md:sp-px-4 sp-text-center">
                    <img src="https://test_magento_image_repo.storage.googleapis.com/color copy.png" alt="Personalized plan">
                    <h3 class="sp-h3 sp-mt-2">Products that work better together</h3>
                    <p class="sp-text-sm">The products you receive are designed to work together and enhance each other, bringing top-notch care to your lawn.</p>
                </div>
                <div class="sp-home__how-it-works-step md:sp-w-1/3 sp-mb-12 md:sp-px-4 sp-text-center">
                    <img src="https://test_magento_image_repo.storage.googleapis.com/color copy 2.png" alt="Products arrive">
                    <h3 class="sp-h3 sp-mt-2">Easy to use and backed by experience.</h3>
                    <p class="sp-text-sm">We've been helping people build beautiful lawns for over 150 years. We'll help you grow a yard that will be the talk of the block!</p>
                </div>
            </div>
        </div>
    </div>

    <hr class="sp-vertical-divider">

    <div class="sp-how__delivery sp-bg-green-4">
        <div class="sp-container sp-py-12">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
                Finally, We Deliver What You Need When You Need It
            </h2>

            <div class="md:sp-flex sp-items-center md:sp--mx-4">
                <div class="md:sp-px-4 md:sp-w-1/2">
                    <img
                        alt="Season Animation"
                        class="sp-block sp-mx-auto"
                        src="https://test_magento_image_repo.storage.googleapis.com/Animation.png"
                    />
                </div>

                <div class="md:sp-px-4 sp-text-center md:sp-text-left md:sp-w-1/2">
                    <h3>We send, you apply—that's it</h3>
                    <p class="sp-mb-8">When your lawn needs something, you'll receive a shipment. When you get it, simply apply the product(s) to your lawn. Seriously, it's as simple as that.</p>
                    <a
                        href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>"
                        class="sp-button sp-button--primary sp-button--get-started sp-mb-12 sp-relative"
                    >
                        Get Started
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="sp-how__program">
        <div class="sp-container sp-py-12">
            <h2 class="sp-h2 sp-max-w-lg sp-mx-auto sp-text-center sp-text-green-1">
            A lawn care plan that works for you.
            </h2>

            <div class="sp-flex sp-flex-column md:sp-flex-row md:sp-flex-wrap sp-items-center md:sp--mx-4">
                <div class="md:sp-w-1/2 sp-mb-12 sp-px-4 sp-order-1 md:sp-order-0">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">Flexible Payments</h3>
                        <p>You can either choose a seasonal subscription (pay per shipment) or save 10% by signing up for an annual subscription (one-time payment).</p>
                    </div>
                </div>
                <div class="md:sp-w-1/2 md:sp-mb-12 sp-order-0 md:sp-order-1 sp-px-4">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/subscription-options.png" alt="Subscription Options">
                    </div>
                </div>
                <div class="md:sp-w-1/2 md:sp-mb-12 sp-order-2 sp-px-4">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/products.png" alt="Product Delivery">
                    </div>
                </div>
                <div class="md:sp-w-1/2 md:sp-flex sp-justify-end sp-mb-12 sp-order-3 sp-px-4">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">Just-in-time delivery</h3>
                        <p>We send your product when you need it. Which means all you need to do is wait for something to arrive and apply it when it does.</p>
                    </div>
                </div>
                <div class="md:sp-w-1/2 sp-mb-12 sp-order-5 md:sp-order-4 sp-px-4">
                    <div class="sp-max-w-sm sp-text-center md:sp-text-left">
                        <h3 class="sp-h3">Bonus: My Lawn companion app</h3>
                        <p>We make it easy to manage your plan with our My Lawn app.</p>
                        <div class="sp-flex sp-justify-center md:sp-justify-start">
                            <a href="https://apps.apple.com/us/app/my-lawn-a-guide-to-lawn-care/id372269879?mt=8" target="_blank">
                                <img
                                    alt="App Store"
                                    class="sp-app-image sp-mr-4"
                                    src="https://test_magento_image_repo.storage.googleapis.com/badge--appstore.png"
                                    style="max-width: 8rem"
                                />
                            </a>
                            <a href="https://play.google.com/store/apps/details?id=com.scotts.lawnapp" target="_blank">
                                <img
                                    alt="Google Play"
                                    class="sp-app-image"
                                    src="https://test_magento_image_repo.storage.googleapis.com/badge--googleplay.png"
                                    style="max-width: 8rem"
                                />
                            </a>
                        </div>
                    </div>
                </div>
                <div class="md:sp-w-1/2 md:sp-mb-8 sp-order-4 md-sp-order-5 sp-px-4">
                    <div class="sp-bg-green-4 sp-flex sp-items-end sp-justify-center">
                        <img src="https://test_magento_image_repo.storage.googleapis.com/apps-bg-green.png" alt="Mobile Apps">
                    </div>
                </div>
            </div>

            <div class="sp-text-center">
                <a
                    href="<?php echo $block->escapeUrl($block->getUrl('quiz')) ?>"
                    class="sp-button sp-button--primary sp-button--get-started sp-mb-12 sp-relative"
                >
                    Get Started
                </a>
            </div>
        </div>
    </div>
</div>
