<?php
//Set Vars
$pcvHeadlineCustomCssStyle = '';
$pcvHeadlineStyleValues = '';
$pcvParagraphTextSize = '';
$pcvBannerTextStyleSelected = '';
$pcvBannerTextStyleValuesSelected = '';
$valueOfTextStyle = '';
$pcvIconColorSelected = '';
$pcvIconBackgroundColorSelected = '';


//If pcvBannerHeadlineStyle exists then set to customCssStyles
if($block->getData('pcvBannerHeadlineStyle') != ''):
    $pcvHeadlineCustomCssStyle = $block->getData('pcvBannerHeadlineStyle');
endif;


//If pcvBannerTextSize exists then set to $pcvParagraphTextSize
if($block->getData('pcvBannerTextSize') != ''):
    $pcvParagraphTextSize = $block->getData('pcvBannerTextSize');
endif;


// If pcvBannerTextStyle exists then set to $pcvBannerTextStyleSelected
if($block->getData('pcvBannerTextStyle') != ''):
  $pcvBannerTextStyleSelected = $block->getData('pcvBannerTextStyle');
endif;


// If pcvIconColor exists then set to $pcvIconColorSelected
if($block->getData('pcvIconColor') != ''):
  $pcvIconColorSelected = $block->getData('pcvIconColor');
endif;


// If pcvIconBackgroundColor exists then set to $pcvIconBackgroundColorSelected
if($block->getData('pcvIconBackgroundColor') != ''):
  $pcvIconBackgroundColorSelected = $block->getData('pcvIconBackgroundColor');
endif;
?>


<section class="product-callout-video-widget product-info-container">
    <div class="product-info grid col-2">
        <div class="productCalloutVideo-imageContainer span_6_of_12">
            <div class="productCalloutVideo-selectedImgContainer" style="background: url('<?php echo $block->getData
            ('pcvCalloutImage'); ?>') no-repeat;
              background-size:cover; background-position:center;">
                <a class="productCalloutVideo-watchVideo play video-link" href="#">
                    <i class="icon-play fas fa-play" style="color:<?php echo $pcvIconColorSelected?>;
                      background-color:<?php echo $pcvIconBackgroundColorSelected?>;"></i>
                    <span class="embed-code">
                        <iframe width="<?php echo $iframeCustomWidth?>" height="<?php echo $iframeCustomHeight?>" src="<?php echo $iframeVideoCustomLink?>" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="" data-dayt="true">
                        </iframe>
                    </span>
                </a>
            </div>
        </div>
        <div class="productCalloutVideo-contentContainer span_6_of_12 <?php echo $block->getData('pcvTextContainerAlignment') ?>">
            <h2 style="<?php
            $pcvHeadlineStyleValues = explode(',', $pcvHeadlineCustomCssStyle);
            foreach($pcvHeadlineStyleValues as $pcvHeadlinevalue) {
              echo $pcvHeadlinevalue;
            } ?>color:<?php echo $block->getData('pcvBannerHeadlineColor');?>;">
                <?php echo $block->getData('pcvBannerHeadline'); ?>
            </h2>
            <p style="<?php echo $pcvParagraphTextSize?>
              <?php
              $pcvBannerTextStyleValuesSelected = explode(',', $pcvBannerTextStyleSelected);
                foreach($pcvBannerTextStyleValuesSelected as $valueOfTextStyle) {
                  echo $valueOfTextStyle;
                }
              ?>
              color:<?php echo $block->getData('pcvBannerTextColor'); ?>;">
              <?php echo $block->getData('pcvBannerText');?>
            </p>
        </div>
        <div id="video-overlay" class="video-overlay"></div>
        <div id="video-container" class="video-container">
            <div class="video-frame"></div>
        </div>
    </div>
</section>