<?php
    $headlines = array('featureoneheadline', 'featuretwoheadline', 'featurethreeheadline', 'featurefourheadline', 'featurefiveheadline');
    $text = array('featureonetext', 'featuretwotext', 'featurethreetext', 'featurefourtext', 'featurefivetext');
    $images = array('featureoneimage', 'featuretwoimage', 'featurethreeimage', 'featurefourimage', 'featurefiveimage');

    $html = '';

    $featureHeadlineCustomStyles = '';

    $featureHeadlineCustomSize = '';

    $featureHeadlineCustomColor = '';

    $featureTextCustomSize = '';

    $featureTextCustomColor = '';

    $featureTextCustomStyles = '';

    $featuresListHeadlineCustomStyles = '';

    //If headlinetextstyle exists then set to $featuresListHeadlineCustomStyles
    if($block->getData('featuresListHeadlineStyles') != ''):
        $featuresListHeadlineCustomStyles = $block->getData('featuresListHeadlineStyles');
    endif;


    //If featuresListHeadlineSize exists then set to $featuresListHeadlineCustomSize
    if($block->getData('featuresListHeadlineSize') != ''):
      $featuresListHeadlineCustomSize = $block->getData('featuresListHeadlineSize');
    endif;


    //If featureHeadlineSize exists then set to $featureHeadlineCustomSize
    if($block->getData('featureHeadlineSize') != ''):
      $featureHeadlineCustomSize = $block->getData('featureHeadlineSize');
    endif;


    //If featureTextSize exists then set to $featureTextCustomSize
    if($block->getData('featureTextSize') != ''):
      $featureTextCustomSize = $block->getData('featureTextSize');
    endif;


    //If featureHeadlineColor exists then set to $featureHeadlineCustomColor
    if($block->getData('featureHeadlineColor') != ''):
      $featureHeadlineCustomColor = $block->getData('featureHeadlineColor');
    endif;


    //If featureTextColor exists then set to $featureHeadlineCustomColor
    if($block->getData('featureTextColor') != ''):
      $featureTextCustomColor = $block->getData('featureTextColor');
    endif;


    //If value exists for featureHeadlineStyles pull in the value and replace the comma for a space
    if($block->getData('featureHeadlineStyles') != ''):
      $featureHeadlineCustomStyles = str_replace(',' , '', $block->getData('featureHeadlineStyles'));
    endif;


    //If value exists for featureTextStyles pull in the value and replace the comma for a space
    if($block->getData('featureTextStyles') != ''):
      $featureTextCustomStyles = str_replace(',' , '', $block->getData('featureTextStyles'));
    endif;




    $i = 0;
    $cols = 0;
    foreach($headlines as $headline):
        if($this->getData($headline) != ''):
            $html .= '<div class="item">
                <div class="image-container">
                    <img src="' . $block->getData($images[$i]) . '" />
                </div>
                <h3 style="' . $featureHeadlineCustomSize . 'color:' . $featureHeadlineCustomColor . '; ' . trim($featureHeadlineCustomStyles) . '">' . $block->getData($headline) . '</h3>
                <p style="' . $featureTextCustomSize . 'color:' . $featureTextCustomColor . '; ' . trim($featureTextCustomStyles) . '">' . $block->getData($text[$i]) . '</p>
            </div>';

            $cols++;
        endif;

        $i++;
    endforeach;
?>
<!-- Old Section:
<section class="<?php echo 'feature-list grid col-' . $cols; ?>">
-->
<section class="<?php echo 'feature-list'?>">
    <h2 style="
      <?php
      $headlinestylevalues = explode(',', $featuresListHeadlineCustomStyles);
      foreach($headlinestylevalues as $headlinevalue) {
          echo $headlinevalue;
      }
      echo $featuresListHeadlineCustomSize;
      ?>color:<?php echo $block->getData('featuresListHeadlineColor')?>;">
      <?php echo $block->getData('featuresListHeadline'); ?></h2>
    <?php echo $html; ?>
</section>
