<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
 
// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div class="actions">
        <a class="action continue"
           href="<?= $block->getUrl('') ?>"
           title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
            <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
        </a>
    </div>
	<div class="actions backbtn">
        <a class="action back"
           href="<?= $block->getUrl('checkout/cart/') ?>"
           title="<?= $block->escapeHtml(__('Back to Cart')) ?>">
            <span><?= /* @escapeNotVerified */ __('Back to Cart') ?></span>
        </a>
    </div>
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/custom": {}
    }
}
</script>
<script type="text/javascript">
 require([
    'jquery',
    'jquery/ui',
    'jquery/validate',
    'mage/translate'
], function($){

    $.validator.addMethod(
        'required-entry', function (value) {
			alert("www");
            if(value) return true;
            else return false;
        }, $.mage.__('Please select a variant!'));
		

});
</script>