<?php
$orderAdd = $block->getOrderInfo();
 if(!empty($orderAdd)){ 
 $additional_information = json_decode($orderAdd['additional_information']);
?>
<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Order #')) ?></th>
                        <td><?= $block->escapeHtml(__('%1', $orderAdd['order_id'])) ?></td>
                    </tr>
                   <tr>
                        <th><?= $block->escapeHtml(__('SAP Order #')) ?></th>
                        <td><?php if(!empty($orderAdd['sap_order_id'])) echo $block->escapeHtml(__($orderAdd['sap_order_id'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Order Status')) ?></th>
                        <td><?php if(!empty($orderAdd['order_status'])) echo $block->escapeHtml(__($orderAdd['order_status'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Invoice #')) ?></th>
                        <td><?php if(!empty($orderAdd['sap_billing_doc_number'])) echo $block->escapeHtml(__($orderAdd['sap_billing_doc_number'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Last 4')) ?></th>
                        <td><?php if(!empty($additional_information->{'last_four'})) echo $block->escapeHtml(__($additional_information->{'last_four'})) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('CC Authorization Transaction #')) ?></th>
                       <td><?php if(!empty($orderAdd['cc_authorization_transaction'])) echo $block->escapeHtml(__($orderAdd['cc_authorization_transaction'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('CC Capture Transaction #')) ?></th>
                        <td><?php if(!empty($orderAdd['cc_capture_transaction'])) echo $block->escapeHtml(__($orderAdd['cc_capture_transaction'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('CC Response')) ?></th>
                        <td><?php if(!empty($orderAdd['cc_response'])) echo $block->escapeHtml(__($orderAdd['cc_response'])) ?></td>
                    </tr>
                     <tr>
                        <th><?= $block->escapeHtml(__('Shipping Description')) ?></th>
                        <td><?php if(!empty($orderAdd['shipping_description'])) echo $block->escapeHtml(__($orderAdd['shipping_description'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('SAP Shipping Code')) ?></th>
                        <td><?php if(!empty($orderAdd['sap_shipping_code'])) echo $block->escapeHtml(__($orderAdd['sap_shipping_code'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Tracking #')) ?></th>
                        <td><?php if(!empty($orderAdd['tracking'])) echo $block->escapeHtml(__($orderAdd['tracking'])) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Delivery Number')) ?></th>
                        <td><?php if(!empty($orderAdd['delivery_number'])) echo $block->escapeHtml(__($orderAdd['delivery_number'])) ?></td>
                    </tr>
                </table>
            </div>
        
    </div>
</section>
<?php } ?>
