<div class="sp-widget">
	<div class="sp-widget-line"></div>
	<?php if( ! empty( $this->getData('contactAddress') ) ) { ?>
	<address class="sp-widget-address">
		<?php echo $block->escapeHtml($block->getData('contactAddress')) ?>
	</address>
	<?php } ?>
	<?php if( ! empty( $this->getData('contactPhone') ) ) { ?>
		<a href="tel:<?php echo $block->escapeHtml($block->getData('contactPhone')) ?>"><?php echo $block->escapeHtml($block->getData('contactPhone')) ?></a>
	<?php } ?>
</div>