<div class="sp-widget sp-widget--contact-form">
	<h2 class="sp sp-h2 sp-text-green-1"><?= $block->escapeHtml($block->getData('contactFormHeading')) ?></h2>
	<p class="sp-text-base"><?= $block->escapeHtml($block->getData('contactFormText')) ?></p>
    <input id="salesForceUrl" type="hidden" value="<?= $block->escapeHtml($block->getData('contactFormSalesForceURL')) ?>" />
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_form')->toHtml(); ?>	
</div>