

<div class="sp-quiz sp-bg-green-1 sp-flex sp-text-white">
    <div class="sp-quiz__wrapper sp-flex sp-flex-column sp-h-full sp-w-full" data-bind="scope: 'quiz'">
        <div
            class="sp-quiz__content sp-flex-auto sp-py-12"
            data-bind="css: { 'sp-quiz--has-address': quiz.questions().length && quiz.questions()[0].questionType === 5 && quiz.map() && quiz.map().address() }"
        >
            <div class="sp-quiz__question-wrapper sp-h-full">
                <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>">
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/1-single-select" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/2-multi-select" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/3-slider" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/4-entry" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/5-zone" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/5-b-zone" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/6-area" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/7-single-select-with-images" --><!-- /ko -->
                <!-- ko template: "SMG_RecommendationQuiz/questiontypes/8-multi-select-with-images" --><!-- /ko -->
            </div>
            <div class="sp-quiz__transition-wrapper">
                <!-- ko template: "SMG_RecommendationQuiz/transition" --><!-- /ko -->
            </div>
        </div>

        <!-- ko template: "SMG_RecommendationQuiz/footer" --><!-- /ko -->
    </div>
</div>

<script
    async
    defer
    src="https://maps.googleapis.com/maps/api/js?key=<?php echo $block->getGoogleMapsApiKey(); ?>&libraries=drawing,geometry,places"
    type="text/javascript"
>
</script>

<script type="text/x-magento-init">
   {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "quiz": {
                        "component": "SMG_RecommendationQuiz/js/quiz"
                    }
                }
            }
        }
    }
</script>
