<div class="sp-faq-page sp-container sp-mb-12">
    <div data-bind="scope: 'sp-faq', childrenComplete: setupAccordion">
        <!-- ko template: getTemplate() --><!-- /ko -->

        <div
            id="faq_list"
            data-bind="afterRender: setupAccordion"
        >
            <div
                id="faq_1"
                class="sp-faq-list"
                data-bind="visible: category() == 'faq_1'"
            >
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('faq_1')->toHtml();?>
            </div>

            <div
                id="faq_2"
                class="sp-faq-list"
                data-bind="visible: category() == 'faq_2'"
            >
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('faq_2')->toHtml();?>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "sp-faq": {
                        "component": "SMG_SPV2FAQPageWidget/js/faq",
                        "template" : "SMG_SPV2FAQPageWidget/faq"
                    }
                }
            }
        }
    }
</script>
