<div class="sp-faq-question" data-role="collapsible">
    <div class="sp-flex sp-items-center sp-faq-pointer" data-role="trigger">
        <img class="sp-faq-open" src="https://test-magento-image-repo.storage.googleapis.com/Icon-Open.png" alt="Expand Question">
        <img class="sp-faq-close" src="https://test-magento-image-repo.storage.googleapis.com/Icon-Close.png" alt="Close Question">
        <span class="sp-h4--long sp-ml-12">
            <?php echo $block->escapeHtml($block->getData('faqQuestion')) ?>
        </span>
    </div>
</div>

<div class="sp-faq-answer sp-ml-12" data-role="content">
    <?php echo $block->escapeHtml($block->getData('faqAnswer')) ?>
</div>

<hr class="sp-faq-divider">
