<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
?>


<?php $_product = $block->getProduct() ?>


<div class="bundle-product-title"><?= $block->escapeHtml($_product->getName()) ?></div>

<div class="bundle-product-description"><?= /* @noEscape */ $_product->getDescription() ?></div>

<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <p class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </p>
    <?php else : ?>
        <p class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </p>
    <?php endif; ?>
<?php endif; ?>
<?= $block->getChildHtml('bundle_prices') ?>
