<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $smghelper = $this->helper('SMG\Launch\Helper\Data'); ?>

<!-- Define Variables -->
<?php
    $i = 1;
    $x = 1;
    $active = '';
?>


<!-- Call JS file using RequireJS -->
<script>
    require(["SMG_GroupedAssociatedProducts/js/product-switcher"]);
</script>


<div class="product attribute grouped-title-section">

    <!-- Grouped Product Name -->
    <h2 class="grouped-product-header"><?= /* @escapeNotVerified */ $_product->getData('name');?></h2>

    <!-- Grouped Short Description -->
  <?= /* @escapeNotVerified */ $_product->getData('short_description');?>
</div>

<!-- Product Select Wrapper -->
<div class="grouped-product-wrapper">
<?php //if($_hasAssociatedProducts):  ?>
        <h5>Choose an Option</h5>
        <select name="selectProduct" id="product_selector">
            <?php foreach ($_associatedProducts as $_values): ?>
			<?php
				$priceHelper = $smghelper->getObjectmanager()->create('Magento\Framework\Pricing\Helper\Data');
				$formattedPrice = $priceHelper->currency($_values->getPrice(), true, false);
			?>
                <option class="product-item-name" price="<?php echo $formattedPrice; ?>" value="<?php echo $_values->getId() ?>" name="<?= /* @escapeNotVerified */
                $_values->getData
                ('entity_id');
                ?>">
                    <? $x++; ?>
                    <?= /* @escapeNotVerified */ $_values->getData('name');?>
          <!-- <?= $_values->getData('entity_id');?>-->
         </option>
        <?php endforeach; ?>
      </select>
<?php //endif: ?>
</div>

<!-- Grouped Table -->
<div class="table-wrapper grouped">
    <table class="table data grouped"
           id="super-product-table"
           data-mage-init='{ "Magento_GroupedProduct/js/product-ids-resolver": {} }'>
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
        <thead>
        <tr class="grouped-table-titles">
            <th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
          <?php if ($_product->isSaleable()): ?>
              <th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
          <?php endif; ?>
        </tr>
        </thead>
      <?php if ($_hasAssociatedProducts): ?>
        <?php //foreach ($_associatedProducts as $_item): ?>
              <tbody>
              <!-- If ID has a 1 then set $active to 'active'-->
              <?php $active = ($i == 1) ? ' active' : '';?>
              <tr class="grouped-row<?php echo $active?>" id="product_summary_id__<?php echo $i;?>">
                    <?php $i++;?>
                    <td class="col item product-detail-td">
                      <!-- Simple Product Short Description -->
                      <?php  //$_item->getData('short_description');?>


                      <!-- Insert Product Price -->
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                      <?php //if ($block->getCanShowProductPrice($_item)): ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                      <?php //endif; ?>
                    <?php endif; ?>
                  </td>
                <?php if ($_product->isSaleable()): ?>
                    <td class="col qty product-qty-td">
                      <?php //if ($_item->isSaleable()) : ?>
                          <div class="control qty">
                              <input type="button" value="-" class="qtyminus box_down<?php //echo $_item->getId(); ?>" id="qtyminus" field="quantity"/>
                              <input type="number"
                                     id=""
                                     name=""
                                     data-selector=""
                                     value="<?= /* @escapeNotVerified */ $_product->getQty() * 1 ?>"
                                     title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                     class="input-text qty qty-group"
                                     data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                     data-errors-message-box="#validation-message-box"/>
                              <input type="button" value="+" id="qtyplus" class="qtyplus" field="quantity"/>
                          </div>
                      <?php //else: ?>

                      <?php //endif; ?>
                    </td>
                <?php endif; ?>
              </tr>

              </tbody>
        <?php //endforeach; ?>
      <?php else: ?>
          <tbody>
          <tr>
              <td class="unavailable"
                  colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                <?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
              </td>
          </tr>
          </tbody>
      <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_GroupedProduct/group": {}
    }
}
</script>
