<?php 

$cart= $this->cartitem();
$cart_id=$cart->getId();
$customer_object = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $customer_object->create('Magento\Customer\Model\Session');
$objectManager     = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$eventarr=array();
$data_arr[] = array();
 $subtotal = $cart->getSubtotal();
 $coupon_code = $cart->getCouponCode();

$sitename=$storeManager->getStore()->getName();

$eventarr['events']=array();
$eventarr['page']=array('cms'=>'M2','type'=>'en|us|store|checkout|cart','site'=>$sitename,'preffered_local'=>'us/ca/mx','rendered_local'=>'en/fr/sp');

foreach ($cart->getAllVisibleItems() as $item) {
	$product = $item->getProduct();
	$_catCollection 		= $item->getProduct()->getCategoryCollection();
	$catname = array();
     foreach ($_catCollection as $_category) {
           $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($_category->getId());
           $catname[] = $cat->getName();
     }

	$data['id'] 	= $item->getId();
	$data['name'] 	= $item->getName();
	$data['brand']  = '';
	$data['category'] = $catname;
	$data['currency'] = 'USD';
	$data['unitPrice'] = $item->getPrice();
	$data['sku'] 	= $item->getSku();
	$data['imageUrl']      = $mediaUrl.'/'.$product->getSmallImage();
	$data['quantity'] = $item->getQty();
    $data['url']  = $product->getProductUrl();
	$data_arr[]= $data;


	}


if ($customerSession->isLoggedIn())
{
	 $userid=$customerSession->getCustomerId();  // get Customer Id
	 $billingAddress = $customerSession->getCustomer()->getDefaultBillingAddress(); 
     if($billingAddress)
     {
       $zip =  $billingAddress->getPostcode();
     }else
     {
     	$zip = '00000';
     }
    $usename = $customerSession->getCustomer()->getName();  // get  Full Name
   	$useremail = $customerSession->getCustomer()->getEmail(); // get Email
    
	$eventarr['user'] = array('userId'=>$userid,'email'=>$useremail,'isLoggedIn'=>1, 'zip'=>$zip, 'cartId'=>$cart_id);
}	
else
{
	$eventarr['user'] = array();
}
$eventarr['cart']=array('currency'=>'USD','subtotal'=>$subtotal,'promoCode'=>$coupon_code,'lineItems'=>$data_arr);
//print_r($eventarr);
?>
<script type="text/javascript">
</script>

