apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magento-local
  name: magento-local-deployment
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: magento-local
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: magento-local
    spec:
      containers:
      - image:  magento-local:0.0.34
        imagePullPolicy: IfNotPresent
        name: local-magento
        ports:
        - containerPort: 80
        env:
        - name: MAGENTO_DB_HOST
          value: local-magento-mysql
        - name: MAGENTO_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-tkbg6h6bkh
              key: password
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /pub/health_check.php
        #     port: 80
        #     scheme: HTTP
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 11
        #   timeoutSeconds: 1
        # resources:
        #   limits:
        #     memory: 5Gi
        #     cpu: 500m
        #   requests:
        #     memory: 1Gi
        #     cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: magento-local-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
#MySQL
# apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
# kind: Deployment
# metadata:
#   name: magento-mysql
#   labels:
#     app: magento-local-mysql
# spec:
#   selector:
#     matchLabels:
#       app: magento-mysql
#       tier: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: magento-mysql
#         tier: mysql
#     spec:
#       containers:
#       - image: mysql:5.7
#         name: mysql
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password
#         ports:
#         - containerPort: 3306
#           name: mysql
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql-persistent-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento-local
  name: magento-local-np
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 80
    protocol: TCP
  selector:
    app: magento-local