<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore()->getCode();
$helper = $block->getHelper();
if (!$helper->isPlegoEnabled($store)) {
	return;
}
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');

$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$cart_id = $cart->getQuote()->getId();
$script = $helper->getScript($store);
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$currentPage = $request->getFullActionName();
$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$subTotal = $cart->getQuote()->getSubtotal();
$items = $cart->getQuote()->getAllItems();

$type = '';
if($currentPage == 'cms_index_index'){
	$type = 'CMS';	
}else if($currentPage == 'catalog_category_view'){
	$type = 'collection';	
}else if($currentPage == 'catalog_product_view'){
	$type = 'product';	
}else if($currentPage == 'checkout_cart_index'){
	$type = 'cart';	
}else if($currentPage == 'checkout_index_index '){
	$type = 'checkout';	
}else if($currentPage == 'customer_account_index'){
	$type = 'customer';	
}else if($currentPage == 'checkout_onepage_success'){
	$type = 'order_success';	
}else if($currentPage == 'catalogsearch_result_index'){
	$type = 'search';	
}      
 

?>
<!-- Adobe Launch Code -->
<script src="<?php echo $script?>"></script>
<script>
   smgData = {
	  events: [],
	  page: {
		cms: 'M2',
		type: '<?php echo $type;?>' 
		site: '<?php echo $store;?>' 
		preffered_local: 'english'
		rendered_local: 'english' 
	  },
	  <?php if($customerSession->isLoggedIn()) {?>
	   user: {
		userId: '<?php echo $customerSession->getCustomer()->getId();?>', 
		email: '<?php echo $customerSession->getCustomer()->getEmail();?>',
		isLoggedIn: 1,
		zip: 	
		cartId: '<?php echo $cart_id;?>'
	  },
	  <?php }else{?>
	  user: {
		userId: '', 
		email: '',
		isLoggedIn: ,
		zip: 
		cartId: '<?php echo $cart_id;?>' 
	  },
	  <?php } ?>
	  cart: {
		currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
		subtotal: <?php echo $subTotal;?>, 
		promoCode: '<?php echo $cart->getQuote()->getCouponCode();?>', 
		lineItems: [ 
		<?php foreach($items as $item) {
			$product = $objectManager->get('Magento\Catalog\Model\Product')->load($item->getProductId());
			$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
			$productImageUrl = '';
			if($product->getImage()){
				$productImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
			}
			$productUrl  = $product->getProductUrl();
			
			$categoryIds = $product->getCategoryIds();
			$categories = $categoryCollection->create()
                                 ->addAttributeToSelect('*')
                                 ->addAttributeToFilter('entity_id', $categoryIds);
			$cats = [];
			foreach ($categories as $category) {
				$cats[] = $category->getName();
			}					 
		?>
		  {
			  id: '<?php echo $item->getProductId();?>',
			  name: '<?php echo $item->getName();?>', 
			  category: [
			  <?php foreach ($categories as $category) {?>
					'<?php echo $category->getName();?>',
			  <?php } ?>
			  ],
			  currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
			  unitPrice: <?php echo $item->getPrice();?>,
			  sku: '<?php echo $item->getSku();?>', 
			  imageUrl: '<?php echo $productImageUrl;?>',  
			  quantity: <?php echo $item->getQty();?>,
			  url: '<?php echo $productUrl;?>'
		  },
		<?php } ?>
		]
	  }
	}
</script>
<?php if($currentPage == 'catalog_category_view'){ 
	$cat = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
	$category = $objectManager->create('Magento\Catalog\Model\Category')->load($cat->getId());
	$product_count = $category->getProductCount();
?>
	
	<script>

	smgData = {
		page: {
			channel: 'catalog',
			content_type: 'productcatalog',
		},
		listing: {
			resultCount:'<?php echo $product_count;?>',
			layout: '<?php if(isset($_REQUEST['product_list_mode'])){ echo $_REQUEST['product_list_mode']; }else{ echo "grid"; } ?>', 
			pageName: '<?php echo $category->getName();?>',
		}
	}
		
	
		<?php if(isset($_REQUEST)){
			$filters = array();
			foreach($_REQUEST as $key=>$data){
				if($key == 'product_list_mode' || $key == 'q' || $key == 'product_list_order'){
					continue;
				} 
				$filters['key'][] = $key;
				$filters['val'][] = $data;
			} ?>
			<?php if(count($filters)>0 ){ ?>
				smgData.events.push({
					name: 'filterApplied',
					filterType: '<?php echo implode(',',$filters['key']);?>',
					filterValue: '<?php echo implode(',',$filters['val']);?>'
				});
			 <?php } ?>	
		<?php }?>
	</script>
<?php }?>

<?php 
if($currentPage == 'catalog_product_view'){ 
	$pro = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
	$product = $objectManager->get('Magento\Catalog\Model\Product')->load($pro->getProductId());

?>
	<script>
	smgData = {
		page: {
			type: 'product',
		},
		product: {
			id: '<?php echo $product->getId()?>',
			product_category_id: '<?php echo implode(',',$product->getCategoryIds());?>',
			purchase_online: <?php echo $product->getStatus();?> 
			name: '<?php echo $product->getName();?> ',
			currency: '<?php echo $cart->getQuote()->getBaseCurrencyCode();?>',
			unitPrice: '<?php echo $product->getPrice(); ?>',
			sku: '<?php echo $product->getSku(); ?>', 
			inStock: <?php echo $product->getIsSalable(); ?> 
		}
	}
		
	</script>
<?php }?>
<?php 
if($currentPage == 'catalogsearch_result_index'){
	
	?>
	<script>
	smgData = {
		page: {
			type: 'search'
		},
		listing: {
			query: '<?php echo $_REQUEST['q'];?>',
			sortBy: '<?php if(isset($_REQUEST['product_list_order'])){ echo $_REQUEST['product_list_order']; }else{ echo "default"; } ?>',
			layout: '<?php if(isset($_REQUEST['product_list_mode'])){ echo $_REQUEST['product_list_mode']; }else{ echo "grid"; } ?>',
			pageName: "<?php echo $block->getLayout()->getBlock('page.main.title')->getPageTitle(); ?>",
		}
	}
		
	</script>

<?php }?>
<!-- End Adobe Launch Code -->
