<div class="sp-footer__grid md:sp-flex md:sp-flex-wrap md:sp--mx-4">
    <div class="sp-footer__brand md:sp-px-4 md:sp-w-1/2">
        <a class="sp-footer__home-link sp-inline-block md:sp-inline-flex sp-items-center sp-justify-start" href="<?= $block->escapeUrl($block->getBaseUrl()) ?>">
            <div class="sp-footer__logo">
                <img src="https://test-magento-image-repo.storage.googleapis.com/scotts_logo@2x.png" alt="Scotts">
            </div>
        </a>
    </div>
	<nav class="sp-footer__social md:sp-px-4 md:sp-w-1/2">
		<ul class="sp-nav-list sp-footer__nav-list sp-footer__nav-list--left">
			<li>
				<a class="sp-link sp-text-white" href="https://www.facebook.com/scottslawn" target="_blank">
					<img class="sp-social-icon" src="https://test-magento-image-repo.storage.googleapis.com/facebook.png" alt="Facebook">
				</a>
			</li>
			<li>
				<a class="sp-link sp-text-white" href="https://twitter.com/scottslawn" target="_blank">
					<img class="sp-social-icon" src="https://test-magento-image-repo.storage.googleapis.com/twitter.png" alt="Twitter">
				</a>
			</li>
			<li>
				<a class="sp-link sp-text-white" href="https://www.instagram.com/scottslawn/" target="_blank">
					<img class="sp-social-icon" src="https://test-magento-image-repo.storage.googleapis.com/instagram.png" alt="Instagram">
				</a>
			</li>
			<li>
				<a class="sp-link sp-text-white" href="https://www.youtube.com/user/ScottsMiracleGro" target="_blank">
					<img class="sp-social-icon" src="https://test-magento-image-repo.storage.googleapis.com/youtube.png" alt="YouTube">
				</a>
			</li>
		</ul>
	</nav>
	<hr class="sp-footer__divider sp-hide md:sp-block md:sp-mx-4">
	<div class="sp-footer__company md:sp-px-4 md:sp-w-1/2">
		<address class="sp-footer__address">
			14111 Scottslawn Rd.<br />
			Marysville, OH 43040
		</address>
		<a class="sp-footer__phone" href="tel:+18882703714">1-888-270-3714</a>
	</div>
	<div class="sp-footer__content md:sp-px-4 sp-text-sm md:sp-w-1/2">
		<nav class="sp-footer__nav">
			<ul class="sp-nav-list sp-footer__nav-list">
                <li>
                    <a class="sp-link" href="/faq">FAQ</a>
                </li>
                <li>
                    <a class="sp-link" href="/returns">Returns</a>
                </li>
                <li>
                    <a class="sp-link" href="/contact">Contact</a>
                </li>
			</ul>
		</nav>
		<p class="sp-p2">
			Google Play and the Google Play logo are trademarks of
			Google Inc.
		</p>
		<p class="sp-p2">
			Apple, the Apple logo, and iPhone are trademarks of
			Apple Inc., registered in the U.S. and other countries.
			App Store is a service mark of Apple Inc., registered in
			the U.S. and other countries.
		</p>
        <p class="sp-mb-8 sp-p2">
            By using this website you agree to our updated
            <a class="sp-p2" href="https://scottsmiraclegro.com/terms-conditions/" target="_blank">Conditions of Use</a>
            and consent to the collection and use of your personal information
            as described in our updated
            <a class="sp-p2" href="https://scottsmiraclegro.com/privacy/" target="_blank">Privacy Notice</a>,
            which includes the
            categories of data we collect and information about your preferences
            and rights.
        </p>
		<p class="sp-p2">
			*Backed by the Scotts No Quibble Guarantee.
		</p>
		<p class="sp-mb-0 sp-p2">
			&copy; <?php /* @noEscape */ echo date('Y') ?> The Scotts Company LLC. World rights reserved.
		</p>
	</div>
</div>
<div class="sp-max-w-xl sp-mx-auto sp-text-center">
	<nav class="sp-footer__nav">
		<ul class="sp-nav-list sp-footer__nav-list sp-footer__nav-secondary-list">
			<li>
				<a class="sp-link" href="https://scottsmiraclegro.com/terms-conditions/" target="_blank">Conditions of use</a>
			</li>
			<li>
				<a class="sp-link" href="https://scottsmiraclegro.com/privacy/" target="_blank">Privacy Notice</a>
			</li>
			<li>
				<a class="sp-link" href="https://scottsmiraclegro.com/privacy/#4_1_tech_cookies" target="_blank">About Cookies</a>
			</li>
			<li>
				<a class="sp-link" href="http://dsar.scottsmiraclegro.com" target="_blank">Do Not Sell My Personal Information</a>
			</li>
			<li>
				<a class="sp-link" href="https://scottsmiraclegro.com/privacy/#10_interest_ads" target="_blank">About Interest&ndash;Based Ads</a>
			</li>
		</ul>
	</nav>
</div>

<script type="text/x-magento-init">
{
  "*": {
    "Magento_Theme/js/liveperson-init": {}
  }
}
</script>

