<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$brmhelper = $this->helper('SMG\Breadcrumbs\Helper\Data');

$isbreadcrumbs = $brmhelper->isProductBreadcrumb();
?>
<?php if($isbreadcrumbs == '1'):?>
<div class="breadcrumbs"></div>
<?php endif; ?>
<script type="text/x-magento-init">
        {
            ".breadcrumbs": <?= $viewModel->getJsonConfigurationHtmlEscaped() ?>
        }
</script>
