<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table class="green"
   style="box-sizing: border-box; border-collapse: separate !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #1d5632; padding: 0 40px;"
   width="100%" bgcolor="#1d5632">
   <tr>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <p class="white"
            style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; margin: 0; margin-bottom: 0; font-size: 16; font-weight: 600; color: #fff;">
            <?= __('Shipped By') ?>
         </p>
      </td>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <p class="white"
            style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; margin: 0; margin-bottom: 0; font-size: 16; font-weight: 600; color: #fff; text-align: center;">
            <?= __('Tracking Number') ?>
         </p>
      </td>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <p class="white"
            style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; margin: 0; margin-bottom: 0; font-size: 16; font-weight: 600; color: #fff; text-align: right; margin-right: 8px;">
            <?= __('Tracking Link') ?>
         </p>
      </td>
   </tr>
</table>
<?php foreach ($_shipment->getAllTracks() as $_item): ?>
<table class="light-green"
   style="box-sizing: border-box; border-collapse: separate !important; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #edf4e1; padding: 10px 40px;"
   width="100%" bgcolor="#edf4e1">
   <tr>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <p
            style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 0;">
            <?= $block->escapeHtml($_item->getTitle()) ?>
         </p>
      </td>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <h3
            style="color: #1d5632; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-weight: 600; line-height: 1.4em; margin: 0; font-size: 18px; margin-bottom: 12px; text-align: center;">
            <?= $block->escapeHtml($_item->getNumber()) ?>
         </h3>
      </td>
      <td style="box-sizing: border-box; font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; vertical-align: top; width: 33%;"
         valign="top">
         <p
            style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 0; text-align: right;">
            <?= $block->getTrackingHtml($_item) ?>
         </p>
      </td>
   </tr>
</table>
<?php endforeach ?>
<?php endif; ?>


