<?php
/**
 * Output Gigya login form html.
 * defined in GigyaIM\view\frontend\layout\customer_account_login.xml
 * The block for this form is - GigyaIM\Block\Form\Gigyalogin which is mapped to Magento Customer block. mapped in di.xml
 *
 * Here: add accounts.showScreenSet to gigyaInit array
 * Full flow (on gigya_script):
 * Call gigya screen sets.
 * Capture Gigya login event.
 * Create and submit registration form.
 * Submit to Gigya model Controller.
 **/

/** @var \Gigya\GigyaIM\Block\Form\GigyaLogin $block */

$display = $block->getData('display');
$placeholderElementId = $display == 'embed' ? 'gigya-login-embed' : 'gigya-login-popup';

?>
<div class="block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <?php if ($display == 'embed'): ?>
            <!-- Gigya login screen placeholder - id can be dynamic: -->
            <div id="<?php echo $placeholderElementId; ?>" class="gigya-login gigya-loader-location"></div>
        <?php endif; ?>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <script>
            // add Raas login screens function to Gigya init.
            window.gigyaInit = window.gigyaInit || [];
            customLangParams = {
                email_already_exists: "<span class='gigya-error-msg-title'>This email is already associated with an account.</span><br><span class='gigya-error-msg-body'>You can log in to your account if you've created one with My Lawn app, Scotts.com, the My Garden app, the Blossom Smart Watering app, the Gro Connect app, or the MiracleGro Twelve app.</span><br><span class='gigya-error-msg-links'><a href='/customer/account/login'>Log In</a> &nbsp;&nbsp; <a href='/customer/account/login#forgot'>Forgot Password?</a></span>"
            };
            console.log(window.location.hash);
            var <?php echo $display; ?>LoginScreenSetParams = {
                screenSet : "<?php echo $block->getLoginDesktopScreensetId() ?>",
                containerID : "<?php echo $placeholderElementId; ?>",
                startScreen : window.location.hash && window.location.hash === '#forgot' ? 'gigya-forgot-password-screen' : 'gigya-login-screen',
                mobileScreenSet : "<?php echo $block->getLoginMobileScreensetId() ?>", // optional - for using separate mobile screen set.
                customLang: customLangParams
            };
            var <?php echo $display; ?>RaasLoginScreen = {"function": "accounts.showScreenSet", "parameters": <?php echo $display; ?>LoginScreenSetParams};
            window.gigyaInit.push(<?php echo $display; ?>RaasLoginScreen);
        </script>
    </div>
</div>
<style>
    .gigya-error-msg-title,
    .gigya-error-msg-body
    {
        width: 100%;
        font-size: 13px;
        line-height: 15px;
        color: #e76468;
        display: inline-block;
        text-align: left;
        font-weight: 700;
    }
    .gigya-error-msg-body {
        font-weight: 300;
        margin-top: 10px;
    }
    .gigya-error-msg-links {
        display: inline-block;
        font-weight: 300;
        font-size: 13px;
        line-height: 15px;
        margin-top: 10px;
        text-align: left;
        width: 100%;
    }
    .gigya-error-msg-links a {
        text-decoration: underline !important;
    }
</style>