<?php
/**
 * Output Gigya login form html.
 * defined in GigyaIM\view\frontend\layout\customer_account_login.xml
 * The block for this form is - GigyaIM\Block\Form\Gigyalogin which is mapped to Magento Customer block. mapped in di.xml
 *
 * Here: add accounts.showScreenSet to gigyaInit array
 * Full flow (on gigya_script):
 * Call gigya screen sets.
 * Capture Gigya login event.
 * Create and submit registration form.
 * Submit to Gigya model Controller.
 **/

/** @var \Gigya\GigyaIM\Block\Form\GigyaLogin $block */

$display = $block->getData('display');
$placeholderElementId = $display == 'embed' ? 'gigya-login-embed' : 'gigya-login-popup';

?>
<div class="block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <?php if ($display == 'embed'): ?>
            <!-- Gigya login screen placeholder - id can be dynamic: -->
            <div id="<?php echo $placeholderElementId; ?>" class="gigya-login gigya-loader-location"></div>
        <?php endif; ?>
        <?php echo $block->getBlockHtml('formkey'); ?>
        <script>
            // Moved this back into a script tag versus x-mage-init because it
            // was causing issues with the Gigya login page not loading.
            window.gigyaInit = window.gigyaInit || [];

            window.gigyaLoginCustomLangParams = {
                email_already_exists: `
                <div class="sp-gigya-error sp-form-error sp-font-bold sp-mb-4 sp--mt-2">This email is already associated with an account.</div>
                <div class="sp-gigya-error sp-form-error sp-mb-4">
                    You can log in to your account if you've created one with the My Lawn app, Scotts.com, the My Garden app, the Blossom Smart Watering app, the Gro Connect app, or the MiracleGro Twelve app.
                </div>
                <div class="sp-flex">
                    <a class="sp-gigya-link sp-mr-4" href="javascript: void(0)" onclick="
                        gigyaChangeScreen('gigya-login-screen')
                    ">Log In</a>
                    <a class="sp-gigya-link" href="javascript: void(0)" onclick="
                        gigyaChangeScreen('gigya-forgot-password-screen')
                    ">Forgot Password</a>
                </div>
            `
            };

            window.gigyaLoginScreenParams = {
                screenSet: "<?php echo $block->getLoginDesktopScreensetId() ?>",
                containerID: "<?php echo $placeholderElementId; ?>",
                startScreen: window.location.hash && (window.location.hash === '#forgot')
                    ? 'gigya-forgot-password-screen'
                    : 'gigya-login-screen',
                mobileScreenSet: "<?php echo $block->getLoginMobileScreensetId() ?>",
                customLang: window.gigyaLoginCustomLangParams,
                display: "<?php echo $display ?>",
                onAfterScreenLoad() { window.scrollTo(0, 0) },
            };

            window.gigyaChangeScreen = (screen) => {
                window.gigya.accounts.switchScreen({
                    screen: screen,
                    screenSet: window.gigyaLoginScreenParams.screenSet,
                    containerID: window.gigyaLoginScreenParams.containerID,
                });
            };

            window.gigyaInit.push({
                'function': 'accounts.showScreenSet',
                parameters: window.gigyaLoginScreenParams,
            });
        </script>
    </div>
</div>
