<?php if($block->getData('heroimage')): ?>
  <h2 class='hero-zip-image'><?php echo $block->getData('heroimage'); ?></h2>
  <h2 class='hero-zip-image-mobile'><?php echo $block->getData('heroimagemobile'); ?></h2>
  <h2 class='hero-zip-supporting-headline'><?php echo $block->getData('herosupportingheadline'); ?></h2>
  <h2 class='hero-zip-headline'><?php echo $block->getData('heroheadline'); ?></h2>
  <h2 class='hero-zip-text'><?php echo $block->getData('herotext'); ?></h2>
  <h2 class='hero-zip-buttontext'><?php echo $block->getData('buttontext'); ?></h2>
  <h2 class='hero-zip-valid-zipcodes'><?php echo $block->getData('validzipcodes'); ?></h2>
<?php endif; ?>



